package org.jetbrains.kotlin.cli.common.arguments;

import java.util.Arrays;
import kotlin.Metadata;
import org.jetbrains.kotlin.config.MavenComparableVersion;

/* JADX INFO: loaded from: /workspace/dex_all/classes11.dex */
@Metadata(d1 = {"\u0000\n\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\u001a\u0016\u0010\u0000\u001a\u00020\u00012\u0006\u0010\u0002\u001a\u00020\u00012\u0006\u0010\u0003\u001a\u00020\u0001¨\u0006\u0004"}, d2 = {"copyCommonCompilerArguments", "Lorg/jetbrains/kotlin/cli/common/arguments/CommonCompilerArguments;", "from", "to", "org.jetbrains.kotlin:cli-base"}, k = MavenComparableVersion.Item.LIST_ITEM, mv = {MavenComparableVersion.Item.LIST_ITEM, MavenComparableVersion.Item.LIST_ITEM, MavenComparableVersion.Item.INTEGER_ITEM}, xi = 48)
public final class CommonCompilerArgumentsCopyGeneratedKt {
    public static final CommonCompilerArguments copyCommonCompilerArguments(CommonCompilerArguments commonCompilerArguments, CommonCompilerArguments commonCompilerArguments2) {
        commonCompilerArguments.getClass();
        commonCompilerArguments2.getClass();
        CommonToolArgumentsCopyGeneratedKt.copyCommonToolArguments(commonCompilerArguments, commonCompilerArguments2);
        commonCompilerArguments2.setAllowAnyScriptsInSourceRoots(commonCompilerArguments.getAllowAnyScriptsInSourceRoots());
        commonCompilerArguments2.setAllowConditionImpliesReturnsContracts(commonCompilerArguments.getAllowConditionImpliesReturnsContracts());
        commonCompilerArguments2.setAllowContractsOnMoreFunctions(commonCompilerArguments.getAllowContractsOnMoreFunctions());
        commonCompilerArguments2.setAllowHoldsinContract(commonCompilerArguments.getAllowHoldsinContract());
        commonCompilerArguments2.setAllowKotlinPackage(commonCompilerArguments.getAllowKotlinPackage());
        commonCompilerArguments2.setAllowReifiedTypeInCatch(commonCompilerArguments.getAllowReifiedTypeInCatch());
        commonCompilerArguments2.setAllowReturnsResultOf(commonCompilerArguments.getAllowReturnsResultOf());
        commonCompilerArguments2.setAnnotationDefaultTarget(commonCompilerArguments.getAnnotationDefaultTarget());
        commonCompilerArguments2.setAnnotationTargetAll(commonCompilerArguments.getAnnotationTargetAll());
        commonCompilerArguments2.setApiVersion(commonCompilerArguments.getApiVersion());
        commonCompilerArguments2.setAutoAdvanceApiVersion(commonCompilerArguments.getAutoAdvanceApiVersion());
        commonCompilerArguments2.setAutoAdvanceLanguageVersion(commonCompilerArguments.getAutoAdvanceLanguageVersion());
        commonCompilerArguments2.setCheckPhaseConditions(commonCompilerArguments.getCheckPhaseConditions());
        commonCompilerArguments2.setCollectionLiterals(commonCompilerArguments.getCollectionLiterals());
        String[] commonSources = commonCompilerArguments.getCommonSources();
        commonCompilerArguments2.setCommonSources((String[]) Arrays.copyOf(commonSources, commonSources.length));
        commonCompilerArguments2.setConsistentDataClassCopyVisibility(commonCompilerArguments.getConsistentDataClassCopyVisibility());
        commonCompilerArguments2.setContextParameters(commonCompilerArguments.getContextParameters());
        commonCompilerArguments2.setContextReceivers(commonCompilerArguments.getContextReceivers());
        commonCompilerArguments2.setContextSensitiveResolution(commonCompilerArguments.getContextSensitiveResolution());
        commonCompilerArguments2.setDataFlowBasedExhaustiveness(commonCompilerArguments.getDataFlowBasedExhaustiveness());
        commonCompilerArguments2.setDebugLevelCompilerChecks(commonCompilerArguments.getDebugLevelCompilerChecks());
        commonCompilerArguments2.setDetailedPerf(commonCompilerArguments.getDetailedPerf());
        commonCompilerArguments2.setDirectJavaActualization(commonCompilerArguments.getDirectJavaActualization());
        commonCompilerArguments2.setDisableDefaultScriptingPlugin(commonCompilerArguments.getDisableDefaultScriptingPlugin());
        String[] disablePhases = commonCompilerArguments.getDisablePhases();
        commonCompilerArguments2.setDisablePhases((String[]) Arrays.copyOf(disablePhases, disablePhases.length));
        commonCompilerArguments2.setDontSortSourceFiles(commonCompilerArguments.getDontSortSourceFiles());
        commonCompilerArguments2.setDontWarnOnErrorSuppression(commonCompilerArguments.getDontWarnOnErrorSuppression());
        commonCompilerArguments2.setDumpArgumentsDir(commonCompilerArguments.getDumpArgumentsDir());
        commonCompilerArguments2.setDumpDirectory(commonCompilerArguments.getDumpDirectory());
        commonCompilerArguments2.setDumpOnlyFqName(commonCompilerArguments.getDumpOnlyFqName());
        commonCompilerArguments2.setDumpPerf(commonCompilerArguments.getDumpPerf());
        commonCompilerArguments2.setExpectActualClasses(commonCompilerArguments.getExpectActualClasses());
        commonCompilerArguments2.setExplicitApi(commonCompilerArguments.getExplicitApi());
        commonCompilerArguments2.setExplicitBackingFields(commonCompilerArguments.getExplicitBackingFields());
        commonCompilerArguments2.setExplicitContextArguments(commonCompilerArguments.getExplicitContextArguments());
        commonCompilerArguments2.setExplicitReturnTypes(commonCompilerArguments.getExplicitReturnTypes());
        String[] fragmentDependencies = commonCompilerArguments.getFragmentDependencies();
        commonCompilerArguments2.setFragmentDependencies((String[]) Arrays.copyOf(fragmentDependencies, fragmentDependencies.length));
        String[] fragmentFriendDependencies = commonCompilerArguments.getFragmentFriendDependencies();
        commonCompilerArguments2.setFragmentFriendDependencies((String[]) Arrays.copyOf(fragmentFriendDependencies, fragmentFriendDependencies.length));
        String[] fragmentRefines = commonCompilerArguments.getFragmentRefines();
        commonCompilerArguments2.setFragmentRefines((String[]) Arrays.copyOf(fragmentRefines, fragmentRefines.length));
        String[] fragmentSources = commonCompilerArguments.getFragmentSources();
        commonCompilerArguments2.setFragmentSources((String[]) Arrays.copyOf(fragmentSources, fragmentSources.length));
        String[] fragments = commonCompilerArguments.getFragments();
        commonCompilerArguments2.setFragments((String[]) Arrays.copyOf(fragments, fragments.length));
        commonCompilerArguments2.setHeaderMode(commonCompilerArguments.getHeaderMode());
        commonCompilerArguments2.setHeaderModeType(commonCompilerArguments.getHeaderModeType());
        commonCompilerArguments2.setIgnoreConstOptimizationErrors(commonCompilerArguments.getIgnoreConstOptimizationErrors());
        commonCompilerArguments2.setIncrementalCompilation(commonCompilerArguments.getIncrementalCompilation());
        commonCompilerArguments2.setInlineClasses(commonCompilerArguments.getInlineClasses());
        commonCompilerArguments2.setIntellijPluginRoot(commonCompilerArguments.getIntellijPluginRoot());
        commonCompilerArguments2.setIntrinsicConstEvaluation(commonCompilerArguments.getIntrinsicConstEvaluation());
        commonCompilerArguments2.setKotlinHome(commonCompilerArguments.getKotlinHome());
        commonCompilerArguments2.setLanguageVersion(commonCompilerArguments.getLanguageVersion());
        commonCompilerArguments2.setLenientMode(commonCompilerArguments.getLenientMode());
        commonCompilerArguments2.setListPhases(commonCompilerArguments.getListPhases());
        commonCompilerArguments2.setLocalTypeAliases(commonCompilerArguments.getLocalTypeAliases());
        String[] manuallyConfiguredFeatures = commonCompilerArguments.getManuallyConfiguredFeatures();
        commonCompilerArguments2.setManuallyConfiguredFeatures((String[]) Arrays.copyOf(manuallyConfiguredFeatures, manuallyConfiguredFeatures.length));
        commonCompilerArguments2.setMetadataKlib(commonCompilerArguments.getMetadataKlib());
        commonCompilerArguments2.setMetadataVersion(commonCompilerArguments.getMetadataVersion());
        commonCompilerArguments2.setMultiDollarInterpolation(commonCompilerArguments.getMultiDollarInterpolation());
        commonCompilerArguments2.setMultiPlatform(commonCompilerArguments.getMultiPlatform());
        commonCompilerArguments2.setNameBasedDestructuring(commonCompilerArguments.getNameBasedDestructuring());
        commonCompilerArguments2.setNestedTypeAliases(commonCompilerArguments.getNestedTypeAliases());
        commonCompilerArguments2.setNewInference(commonCompilerArguments.getNewInference());
        commonCompilerArguments2.setNoCheckActual(commonCompilerArguments.getNoCheckActual());
        commonCompilerArguments2.setNoInline(commonCompilerArguments.getNoInline());
        commonCompilerArguments2.setNonLocalBreakContinue(commonCompilerArguments.getNonLocalBreakContinue());
        String[] optIn = commonCompilerArguments.getOptIn();
        commonCompilerArguments2.setOptIn((String[]) Arrays.copyOf(optIn, optIn.length));
        String[] phasesToDump = commonCompilerArguments.getPhasesToDump();
        commonCompilerArguments2.setPhasesToDump((String[]) Arrays.copyOf(phasesToDump, phasesToDump.length));
        String[] phasesToDumpAfter = commonCompilerArguments.getPhasesToDumpAfter();
        commonCompilerArguments2.setPhasesToDumpAfter((String[]) Arrays.copyOf(phasesToDumpAfter, phasesToDumpAfter.length));
        String[] phasesToDumpBefore = commonCompilerArguments.getPhasesToDumpBefore();
        commonCompilerArguments2.setPhasesToDumpBefore((String[]) Arrays.copyOf(phasesToDumpBefore, phasesToDumpBefore.length));
        String[] phasesToValidate = commonCompilerArguments.getPhasesToValidate();
        commonCompilerArguments2.setPhasesToValidate((String[]) Arrays.copyOf(phasesToValidate, phasesToValidate.length));
        String[] phasesToValidateAfter = commonCompilerArguments.getPhasesToValidateAfter();
        commonCompilerArguments2.setPhasesToValidateAfter((String[]) Arrays.copyOf(phasesToValidateAfter, phasesToValidateAfter.length));
        String[] phasesToValidateBefore = commonCompilerArguments.getPhasesToValidateBefore();
        commonCompilerArguments2.setPhasesToValidateBefore((String[]) Arrays.copyOf(phasesToValidateBefore, phasesToValidateBefore.length));
        String[] pluginClasspaths = commonCompilerArguments.getPluginClasspaths();
        commonCompilerArguments2.setPluginClasspaths((String[]) Arrays.copyOf(pluginClasspaths, pluginClasspaths.length));
        String[] pluginConfigurations = commonCompilerArguments.getPluginConfigurations();
        commonCompilerArguments2.setPluginConfigurations((String[]) Arrays.copyOf(pluginConfigurations, pluginConfigurations.length));
        String[] pluginOptions = commonCompilerArguments.getPluginOptions();
        commonCompilerArguments2.setPluginOptions((String[]) Arrays.copyOf(pluginOptions, pluginOptions.length));
        String[] pluginOrderConstraints = commonCompilerArguments.getPluginOrderConstraints();
        commonCompilerArguments2.setPluginOrderConstraints((String[]) Arrays.copyOf(pluginOrderConstraints, pluginOrderConstraints.length));
        commonCompilerArguments2.setPrintConfiguration(commonCompilerArguments.getPrintConfiguration());
        commonCompilerArguments2.setProfilePhases(commonCompilerArguments.getProfilePhases());
        commonCompilerArguments2.setProgressiveMode(commonCompilerArguments.getProgressiveMode());
        commonCompilerArguments2.setRenderInternalDiagnosticNames(commonCompilerArguments.getRenderInternalDiagnosticNames());
        commonCompilerArguments2.setRepl(commonCompilerArguments.getRepl());
        commonCompilerArguments2.setReportAllWarnings(commonCompilerArguments.getReportAllWarnings());
        commonCompilerArguments2.setReportOutputFiles(commonCompilerArguments.getReportOutputFiles());
        commonCompilerArguments2.setReportPerf(commonCompilerArguments.getReportPerf());
        commonCompilerArguments2.setReturnValueChecker(commonCompilerArguments.getReturnValueChecker());
        commonCompilerArguments2.setScript(commonCompilerArguments.getScript());
        commonCompilerArguments2.setSeparateKmpCompilationScheme(commonCompilerArguments.getSeparateKmpCompilationScheme());
        commonCompilerArguments2.setSkipMetadataVersionCheck(commonCompilerArguments.getSkipMetadataVersionCheck());
        commonCompilerArguments2.setSkipPrereleaseCheck(commonCompilerArguments.getSkipPrereleaseCheck());
        commonCompilerArguments2.setStdlibCompilation(commonCompilerArguments.getStdlibCompilation());
        commonCompilerArguments2.setSuppressApiVersionGreaterThanLanguageVersionError(commonCompilerArguments.getSuppressApiVersionGreaterThanLanguageVersionError());
        commonCompilerArguments2.setSuppressVersionWarnings(commonCompilerArguments.getSuppressVersionWarnings());
        String[] suppressedDiagnostics = commonCompilerArguments.getSuppressedDiagnostics();
        commonCompilerArguments2.setSuppressedDiagnostics((String[]) Arrays.copyOf(suppressedDiagnostics, suppressedDiagnostics.length));
        commonCompilerArguments2.setUnrestrictedBuilderInference(commonCompilerArguments.getUnrestrictedBuilderInference());
        commonCompilerArguments2.setUseFirExperimentalCheckers(commonCompilerArguments.getUseFirExperimentalCheckers());
        commonCompilerArguments2.setUseFirIC(commonCompilerArguments.getUseFirIC());
        commonCompilerArguments2.setUseFirLT(commonCompilerArguments.getUseFirLT());
        commonCompilerArguments2.setUseK2(commonCompilerArguments.getUseK2());
        String[] verbosePhases = commonCompilerArguments.getVerbosePhases();
        commonCompilerArguments2.setVerbosePhases((String[]) Arrays.copyOf(verbosePhases, verbosePhases.length));
        commonCompilerArguments2.setVerifyIr(commonCompilerArguments.getVerifyIr());
        commonCompilerArguments2.setVerifyIrNestedOffsets(commonCompilerArguments.getVerifyIrNestedOffsets());
        commonCompilerArguments2.setVerifyIrVisibility(commonCompilerArguments.getVerifyIrVisibility());
        String[] warningLevels = commonCompilerArguments.getWarningLevels();
        commonCompilerArguments2.setWarningLevels((String[]) Arrays.copyOf(warningLevels, warningLevels.length));
        commonCompilerArguments2.setWhenGuards(commonCompilerArguments.getWhenGuards());
        return commonCompilerArguments2;
    }
}
