package org.jetbrains.kotlin.cli.common.arguments;

import java.util.Arrays;
import kotlin.Metadata;
import org.jetbrains.kotlin.config.MavenComparableVersion;

/* JADX INFO: loaded from: /workspace/dex_all/classes11.dex */
@Metadata(d1 = {"\u0000\n\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\u001a\u0016\u0010\u0000\u001a\u00020\u00012\u0006\u0010\u0002\u001a\u00020\u00012\u0006\u0010\u0003\u001a\u00020\u0001¨\u0006\u0004"}, d2 = {"copyK2NativeCompilerArguments", "Lorg/jetbrains/kotlin/cli/common/arguments/K2NativeCompilerArguments;", "from", "to", "org.jetbrains.kotlin:cli-base"}, k = MavenComparableVersion.Item.LIST_ITEM, mv = {MavenComparableVersion.Item.LIST_ITEM, MavenComparableVersion.Item.LIST_ITEM, MavenComparableVersion.Item.INTEGER_ITEM}, xi = 48)
public final class K2NativeCompilerArgumentsCopyGeneratedKt {
    public static final K2NativeCompilerArguments copyK2NativeCompilerArguments(K2NativeCompilerArguments k2NativeCompilerArguments, K2NativeCompilerArguments k2NativeCompilerArguments2) {
        k2NativeCompilerArguments.getClass();
        k2NativeCompilerArguments2.getClass();
        CommonKlibBasedCompilerArgumentsCopyGeneratedKt.copyCommonKlibBasedCompilerArguments(k2NativeCompilerArguments, k2NativeCompilerArguments2);
        k2NativeCompilerArguments2.setAllocator(k2NativeCompilerArguments.getAllocator());
        k2NativeCompilerArguments2.setAutoCacheDir(k2NativeCompilerArguments.getAutoCacheDir());
        String[] autoCacheableFrom = k2NativeCompilerArguments.getAutoCacheableFrom();
        k2NativeCompilerArguments2.setAutoCacheableFrom((String[]) Arrays.copyOf(autoCacheableFrom, autoCacheableFrom.length));
        k2NativeCompilerArguments2.setBackendThreads(k2NativeCompilerArguments.getBackendThreads());
        String[] binaryOptions = k2NativeCompilerArguments.getBinaryOptions();
        k2NativeCompilerArguments2.setBinaryOptions((String[]) Arrays.copyOf(binaryOptions, binaryOptions.length));
        k2NativeCompilerArguments2.setBundleId(k2NativeCompilerArguments.getBundleId());
        String[] cacheDirectories = k2NativeCompilerArguments.getCacheDirectories();
        k2NativeCompilerArguments2.setCacheDirectories((String[]) Arrays.copyOf(cacheDirectories, cacheDirectories.length));
        String[] cachedLibraries = k2NativeCompilerArguments.getCachedLibraries();
        k2NativeCompilerArguments2.setCachedLibraries((String[]) Arrays.copyOf(cachedLibraries, cachedLibraries.length));
        k2NativeCompilerArguments2.setCheckDependencies(k2NativeCompilerArguments.getCheckDependencies());
        k2NativeCompilerArguments2.setCheckExternalCalls(k2NativeCompilerArguments.getCheckExternalCalls());
        String[] clangOptions = k2NativeCompilerArguments.getClangOptions();
        k2NativeCompilerArguments2.setClangOptions((String[]) Arrays.copyOf(clangOptions, clangOptions.length));
        k2NativeCompilerArguments2.setCompileFromBitcode(k2NativeCompilerArguments.getCompileFromBitcode());
        k2NativeCompilerArguments2.setDebug(k2NativeCompilerArguments.getDebug());
        k2NativeCompilerArguments2.setDebugInfoFormatVersion(k2NativeCompilerArguments.getDebugInfoFormatVersion());
        String[] debugPrefixMap = k2NativeCompilerArguments.getDebugPrefixMap();
        k2NativeCompilerArguments2.setDebugPrefixMap((String[]) Arrays.copyOf(debugPrefixMap, debugPrefixMap.length));
        k2NativeCompilerArguments2.setDestroyRuntimeMode(k2NativeCompilerArguments.getDestroyRuntimeMode());
        k2NativeCompilerArguments2.setEmitLazyObjCHeader(k2NativeCompilerArguments.getEmitLazyObjCHeader());
        k2NativeCompilerArguments2.setEnableAssertions(k2NativeCompilerArguments.getEnableAssertions());
        k2NativeCompilerArguments2.setExportKDoc(k2NativeCompilerArguments.getExportKDoc());
        String[] exportedLibraries = k2NativeCompilerArguments.getExportedLibraries();
        k2NativeCompilerArguments2.setExportedLibraries((String[]) Arrays.copyOf(exportedLibraries, exportedLibraries.length));
        k2NativeCompilerArguments2.setExternalDependencies(k2NativeCompilerArguments.getExternalDependencies());
        k2NativeCompilerArguments2.setFakeOverrideValidator(k2NativeCompilerArguments.getFakeOverrideValidator());
        String[] filesToCache = k2NativeCompilerArguments.getFilesToCache();
        k2NativeCompilerArguments2.setFilesToCache((String[]) Arrays.copyOf(filesToCache, filesToCache.length));
        String[] frameworkImportHeaders = k2NativeCompilerArguments.getFrameworkImportHeaders();
        k2NativeCompilerArguments2.setFrameworkImportHeaders((String[]) Arrays.copyOf(frameworkImportHeaders, frameworkImportHeaders.length));
        k2NativeCompilerArguments2.setFriendModules(k2NativeCompilerArguments.getFriendModules());
        k2NativeCompilerArguments2.setGc(k2NativeCompilerArguments.getGc());
        k2NativeCompilerArguments2.setGenerateDebugTrampolineString(k2NativeCompilerArguments.getGenerateDebugTrampolineString());
        k2NativeCompilerArguments2.setGenerateNoExitTestRunner(k2NativeCompilerArguments.getGenerateNoExitTestRunner());
        k2NativeCompilerArguments2.setGenerateTestRunner(k2NativeCompilerArguments.getGenerateTestRunner());
        k2NativeCompilerArguments2.setGenerateWorkerTestRunner(k2NativeCompilerArguments.getGenerateWorkerTestRunner());
        k2NativeCompilerArguments2.setHeaderKlibPath(k2NativeCompilerArguments.getHeaderKlibPath());
        String[] includeBinaries = k2NativeCompilerArguments.getIncludeBinaries();
        k2NativeCompilerArguments2.setIncludeBinaries((String[]) Arrays.copyOf(includeBinaries, includeBinaries.length));
        String[] includes = k2NativeCompilerArguments.getIncludes();
        k2NativeCompilerArguments2.setIncludes((String[]) Arrays.copyOf(includes, includes.length));
        k2NativeCompilerArguments2.setIncrementalCacheDir(k2NativeCompilerArguments.getIncrementalCacheDir());
        k2NativeCompilerArguments2.setKonanDataDir(k2NativeCompilerArguments.getKonanDataDir());
        String[] libraries = k2NativeCompilerArguments.getLibraries();
        k2NativeCompilerArguments2.setLibraries((String[]) Arrays.copyOf(libraries, libraries.length));
        k2NativeCompilerArguments2.setLibraryToAddToCache(k2NativeCompilerArguments.getLibraryToAddToCache());
        k2NativeCompilerArguments2.setLibraryVersion(k2NativeCompilerArguments.getLibraryVersion());
        k2NativeCompilerArguments2.setLightDebugDeprecated(k2NativeCompilerArguments.getLightDebugDeprecated());
        k2NativeCompilerArguments2.setLightDebugString(k2NativeCompilerArguments.getLightDebugString());
        String[] linkerArguments = k2NativeCompilerArguments.getLinkerArguments();
        k2NativeCompilerArguments2.setLinkerArguments((String[]) Arrays.copyOf(linkerArguments, linkerArguments.length));
        k2NativeCompilerArguments2.setListTargets(k2NativeCompilerArguments.getListTargets());
        k2NativeCompilerArguments2.setLlvmLTOPasses(k2NativeCompilerArguments.getLlvmLTOPasses());
        k2NativeCompilerArguments2.setLlvmModulePasses(k2NativeCompilerArguments.getLlvmModulePasses());
        k2NativeCompilerArguments2.setLlvmVariant(k2NativeCompilerArguments.getLlvmVariant());
        k2NativeCompilerArguments2.setMainPackage(k2NativeCompilerArguments.getMainPackage());
        k2NativeCompilerArguments2.setMakePerFileCache(k2NativeCompilerArguments.getMakePerFileCache());
        k2NativeCompilerArguments2.setManifestFile(k2NativeCompilerArguments.getManifestFile());
        String[] manifestNativeTargets = k2NativeCompilerArguments.getManifestNativeTargets();
        k2NativeCompilerArguments2.setManifestNativeTargets((String[]) Arrays.copyOf(manifestNativeTargets, manifestNativeTargets.length));
        k2NativeCompilerArguments2.setMemoryModel(k2NativeCompilerArguments.getMemoryModel());
        k2NativeCompilerArguments2.setModuleName(k2NativeCompilerArguments.getModuleName());
        String[] nativeLibraries = k2NativeCompilerArguments.getNativeLibraries();
        k2NativeCompilerArguments2.setNativeLibraries((String[]) Arrays.copyOf(nativeLibraries, nativeLibraries.length));
        k2NativeCompilerArguments2.setNoObjcGenerics(k2NativeCompilerArguments.getNoObjcGenerics());
        k2NativeCompilerArguments2.setNodefaultlibs(k2NativeCompilerArguments.getNodefaultlibs());
        k2NativeCompilerArguments2.setNoendorsedlibs(k2NativeCompilerArguments.getNoendorsedlibs());
        k2NativeCompilerArguments2.setNomain(k2NativeCompilerArguments.getNomain());
        k2NativeCompilerArguments2.setNopack(k2NativeCompilerArguments.getNopack());
        k2NativeCompilerArguments2.setNostdlib(k2NativeCompilerArguments.getNostdlib());
        k2NativeCompilerArguments2.setOmitFrameworkBinary(k2NativeCompilerArguments.getOmitFrameworkBinary());
        k2NativeCompilerArguments2.setOptimization(k2NativeCompilerArguments.getOptimization());
        k2NativeCompilerArguments2.setOutputName(k2NativeCompilerArguments.getOutputName());
        String[] overrideKonanProperties = k2NativeCompilerArguments.getOverrideKonanProperties();
        k2NativeCompilerArguments2.setOverrideKonanProperties((String[]) Arrays.copyOf(overrideKonanProperties, overrideKonanProperties.length));
        k2NativeCompilerArguments2.setPreLinkCaches(k2NativeCompilerArguments.getPreLinkCaches());
        k2NativeCompilerArguments2.setPrintBitCode(k2NativeCompilerArguments.getPrintBitCode());
        k2NativeCompilerArguments2.setPrintFiles(k2NativeCompilerArguments.getPrintFiles());
        k2NativeCompilerArguments2.setPrintIr(k2NativeCompilerArguments.getPrintIr());
        k2NativeCompilerArguments2.setProduce(k2NativeCompilerArguments.getProduce());
        k2NativeCompilerArguments2.setPropertyLazyInitialization(k2NativeCompilerArguments.getPropertyLazyInitialization());
        k2NativeCompilerArguments2.setPurgeUserLibs(k2NativeCompilerArguments.getPurgeUserLibs());
        String[] refinesPaths = k2NativeCompilerArguments.getRefinesPaths();
        k2NativeCompilerArguments2.setRefinesPaths((String[]) Arrays.copyOf(refinesPaths, refinesPaths.length));
        k2NativeCompilerArguments2.setRuntimeFile(k2NativeCompilerArguments.getRuntimeFile());
        k2NativeCompilerArguments2.setRuntimeLogs(k2NativeCompilerArguments.getRuntimeLogs());
        k2NativeCompilerArguments2.setSaveDependenciesPath(k2NativeCompilerArguments.getSaveDependenciesPath());
        String[] saveLlvmIrAfter = k2NativeCompilerArguments.getSaveLlvmIrAfter();
        k2NativeCompilerArguments2.setSaveLlvmIrAfter((String[]) Arrays.copyOf(saveLlvmIrAfter, saveLlvmIrAfter.length));
        k2NativeCompilerArguments2.setSaveLlvmIrDirectory(k2NativeCompilerArguments.getSaveLlvmIrDirectory());
        k2NativeCompilerArguments2.setSerializedDependencies(k2NativeCompilerArguments.getSerializedDependencies());
        k2NativeCompilerArguments2.setShortModuleName(k2NativeCompilerArguments.getShortModuleName());
        String[] singleLinkerArguments = k2NativeCompilerArguments.getSingleLinkerArguments();
        k2NativeCompilerArguments2.setSingleLinkerArguments((String[]) Arrays.copyOf(singleLinkerArguments, singleLinkerArguments.length));
        k2NativeCompilerArguments2.setStaticFramework(k2NativeCompilerArguments.getStaticFramework());
        k2NativeCompilerArguments2.setTarget(k2NativeCompilerArguments.getTarget());
        k2NativeCompilerArguments2.setTemporaryFilesDir(k2NativeCompilerArguments.getTemporaryFilesDir());
        k2NativeCompilerArguments2.setTestDumpOutputPath(k2NativeCompilerArguments.getTestDumpOutputPath());
        k2NativeCompilerArguments2.setVerifyBitCode(k2NativeCompilerArguments.getVerifyBitCode());
        k2NativeCompilerArguments2.setVerifyCompiler(k2NativeCompilerArguments.getVerifyCompiler());
        k2NativeCompilerArguments2.setWorkerExceptionHandling(k2NativeCompilerArguments.getWorkerExceptionHandling());
        k2NativeCompilerArguments2.setWriteDependenciesOfProducedKlibTo(k2NativeCompilerArguments.getWriteDependenciesOfProducedKlibTo());
        return k2NativeCompilerArguments2;
    }
}
