package org.jetbrains.kotlin;

import com.intellij.psi.tree.IElementType;
import com.intellij.psi.tree.IFileElementType;
import org.jetbrains.kotlin.idea.KotlinLanguage;
import org.jetbrains.kotlin.psi.KtAnnotatedExpression;
import org.jetbrains.kotlin.psi.KtArrayAccessExpression;
import org.jetbrains.kotlin.psi.KtBinaryExpression;
import org.jetbrains.kotlin.psi.KtBinaryExpressionWithTypeRHS;
import org.jetbrains.kotlin.psi.KtBreakExpression;
import org.jetbrains.kotlin.psi.KtCallableReferenceExpression;
import org.jetbrains.kotlin.psi.KtCatchClause;
import org.jetbrains.kotlin.psi.KtConstructorDelegationCall;
import org.jetbrains.kotlin.psi.KtConstructorDelegationReferenceExpression;
import org.jetbrains.kotlin.psi.KtContainerNode;
import org.jetbrains.kotlin.psi.KtContainerNodeForControlStructureBody;
import org.jetbrains.kotlin.psi.KtContinueExpression;
import org.jetbrains.kotlin.psi.KtDestructuringDeclaration;
import org.jetbrains.kotlin.psi.KtDestructuringDeclarationEntry;
import org.jetbrains.kotlin.psi.KtDoWhileExpression;
import org.jetbrains.kotlin.psi.KtFinallySection;
import org.jetbrains.kotlin.psi.KtForExpression;
import org.jetbrains.kotlin.psi.KtFunctionLiteral;
import org.jetbrains.kotlin.psi.KtIfExpression;
import org.jetbrains.kotlin.psi.KtIsExpression;
import org.jetbrains.kotlin.psi.KtLabelReferenceExpression;
import org.jetbrains.kotlin.psi.KtLabeledExpression;
import org.jetbrains.kotlin.psi.KtObjectLiteralExpression;
import org.jetbrains.kotlin.psi.KtOperationReferenceExpression;
import org.jetbrains.kotlin.psi.KtParenthesizedExpression;
import org.jetbrains.kotlin.psi.KtPostfixExpression;
import org.jetbrains.kotlin.psi.KtPrefixExpression;
import org.jetbrains.kotlin.psi.KtPropertyDelegate;
import org.jetbrains.kotlin.psi.KtReturnExpression;
import org.jetbrains.kotlin.psi.KtSafeQualifiedExpression;
import org.jetbrains.kotlin.psi.KtSuperExpression;
import org.jetbrains.kotlin.psi.KtThisExpression;
import org.jetbrains.kotlin.psi.KtThrowExpression;
import org.jetbrains.kotlin.psi.KtTryExpression;
import org.jetbrains.kotlin.psi.KtWhenConditionInRange;
import org.jetbrains.kotlin.psi.KtWhenConditionIsPattern;
import org.jetbrains.kotlin.psi.KtWhenConditionWithExpression;
import org.jetbrains.kotlin.psi.KtWhenEntry;
import org.jetbrains.kotlin.psi.KtWhenEntryGuard;
import org.jetbrains.kotlin.psi.KtWhenExpression;
import org.jetbrains.kotlin.psi.KtWhileExpression;
import org.jetbrains.kotlin.psi.stubs.elements.KtStubElementType;

/* JADX INFO: loaded from: /workspace/dex_all/classes11.dex */
public interface KtNodeTypes {
    public static final IElementType ANNOTATED_EXPRESSION;
    public static final IElementType ANNOTATION;
    public static final IElementType ANNOTATION_ENTRY;
    public static final IElementType ANNOTATION_TARGET;
    public static final IElementType ARRAY_ACCESS_EXPRESSION;
    public static final IElementType BACKING_FIELD;
    public static final IElementType BINARY_EXPRESSION;
    public static final IElementType BINARY_WITH_TYPE;
    public static final IElementType BLOCK;
    public static final IFileElementType BLOCK_CODE_FRAGMENT;
    public static final IElementType BODY;
    public static final IElementType BOOLEAN_CONSTANT;
    public static final IElementType BREAK;
    public static final IElementType CALLABLE_REFERENCE_EXPRESSION;
    public static final IElementType CALL_EXPRESSION;
    public static final IElementType CATCH;
    public static final IElementType CHARACTER_CONSTANT;
    public static final IElementType CLASS_BODY;
    public static final IElementType CLASS_LITERAL_EXPRESSION;
    public static final IElementType COLLECTION_LITERAL_EXPRESSION;
    public static final IElementType CONDITION;
    public static final IElementType CONSTRUCTOR_CALLEE;
    public static final IElementType CONSTRUCTOR_DELEGATION_CALL;
    public static final IElementType CONSTRUCTOR_DELEGATION_REFERENCE;
    public static final IElementType CONTEXT_PARAMETER_LIST;

    @Deprecated
    public static final IElementType CONTEXT_RECEIVER_LIST;
    public static final IElementType CONTINUE;
    public static final IElementType CONTRACT_EFFECT;
    public static final IElementType CONTRACT_EFFECT_LIST;
    public static final IElementType DELEGATED_SUPER_TYPE_ENTRY;
    public static final IElementType DOT_QUALIFIED_EXPRESSION;
    public static final IElementType DO_WHILE;
    public static final IElementType DYNAMIC_TYPE;
    public static final IElementType ELSE;
    public static final IElementType ENUM_ENTRY_SUPERCLASS_REFERENCE_EXPRESSION;
    public static final IElementType ESCAPE_STRING_TEMPLATE_ENTRY;
    public static final IFileElementType EXPRESSION_CODE_FRAGMENT;
    public static final IElementType FILE_ANNOTATION_LIST;
    public static final IElementType FINALLY;
    public static final IElementType FLOAT_CONSTANT;
    public static final IElementType FOR;
    public static final IElementType FUNCTION_LITERAL;
    public static final IElementType FUNCTION_TYPE;
    public static final IElementType FUNCTION_TYPE_RECEIVER;
    public static final IElementType IF;
    public static final IElementType IMPORT_ALIAS;
    public static final IElementType IMPORT_DIRECTIVE;
    public static final IElementType IMPORT_LIST;
    public static final IElementType INDICES;
    public static final IElementType INITIALIZER_LIST;
    public static final IElementType INTEGER_CONSTANT;
    public static final IElementType INTERSECTION_TYPE;
    public static final IElementType IS_EXPRESSION;
    public static final IElementType LABEL;
    public static final IElementType LABELED_EXPRESSION;
    public static final IElementType LABEL_QUALIFIER;
    public static final IElementType LAMBDA_ARGUMENT;
    public static final IElementType LAMBDA_EXPRESSION;
    public static final IElementType LITERAL_STRING_TEMPLATE_ENTRY;
    public static final IElementType LONG_STRING_TEMPLATE_ENTRY;
    public static final IElementType LOOP_RANGE;
    public static final IElementType MODIFIER_LIST;
    public static final IElementType NULL;
    public static final IElementType NULLABLE_TYPE;
    public static final IElementType OBJECT_LITERAL;
    public static final IElementType OPERATION_REFERENCE;
    public static final IElementType PACKAGE_DIRECTIVE;
    public static final IElementType PARENTHESIZED;
    public static final IElementType POSTFIX_EXPRESSION;
    public static final IElementType PREFIX_EXPRESSION;
    public static final IElementType PROPERTY_ACCESSOR;
    public static final IElementType PROPERTY_DELEGATE;
    public static final IElementType REFERENCE_EXPRESSION;
    public static final IElementType RETURN;
    public static final IElementType SAFE_ACCESS_EXPRESSION;
    public static final IElementType SCRIPT;
    public static final IElementType SHORT_STRING_TEMPLATE_ENTRY;
    public static final IElementType STRING_INTERPOLATION_PREFIX;
    public static final IElementType STRING_TEMPLATE;
    public static final IElementType SUPER_EXPRESSION;
    public static final IElementType SUPER_TYPE_CALL_ENTRY;
    public static final IElementType SUPER_TYPE_ENTRY;
    public static final IElementType SUPER_TYPE_LIST;
    public static final IElementType THEN;
    public static final IElementType THIS_EXPRESSION;
    public static final IElementType THROW;
    public static final IElementType TRY;
    public static final IElementType TYPE_ARGUMENT_LIST;
    public static final IFileElementType TYPE_CODE_FRAGMENT;
    public static final IElementType TYPE_CONSTRAINT;
    public static final IElementType TYPE_CONSTRAINT_LIST;
    public static final IElementType TYPE_PARAMETER;
    public static final IElementType TYPE_PARAMETER_LIST;
    public static final IElementType TYPE_PROJECTION;
    public static final IElementType TYPE_REFERENCE;
    public static final IElementType USER_TYPE;
    public static final IElementType VALUE_ARGUMENT;
    public static final IElementType VALUE_ARGUMENT_LIST;
    public static final IElementType VALUE_ARGUMENT_NAME;
    public static final IElementType VALUE_PARAMETER;
    public static final IElementType VALUE_PARAMETER_LIST;
    public static final IElementType WHEN;
    public static final IElementType WHEN_CONDITION_EXPRESSION;
    public static final IElementType WHEN_CONDITION_IN_RANGE;
    public static final IElementType WHEN_CONDITION_IS_PATTERN;
    public static final IElementType WHEN_ENTRY;
    public static final IElementType WHEN_ENTRY_GUARD;
    public static final IElementType WHILE;
    public static final IFileElementType FILE = KtStubBasedElementTypes.FILE;
    public static final IFileElementType KT_FILE = new IFileElementType(KotlinLanguage.INSTANCE);
    public static final IElementType CLASS = KtStubBasedElementTypes.CLASS;
    public static final IElementType FUN = KtStubBasedElementTypes.FUNCTION;
    public static final IElementType PROPERTY = KtStubBasedElementTypes.PROPERTY;
    public static final IElementType DESTRUCTURING_DECLARATION = new KtNodeType("DESTRUCTURING_DECLARATION", KtDestructuringDeclaration.class);
    public static final IElementType DESTRUCTURING_DECLARATION_ENTRY = new KtNodeType("DESTRUCTURING_DECLARATION_ENTRY", KtDestructuringDeclarationEntry.class);
    public static final IElementType OBJECT_DECLARATION = KtStubBasedElementTypes.OBJECT_DECLARATION;
    public static final IElementType TYPEALIAS = KtStubBasedElementTypes.TYPEALIAS;
    public static final IElementType COMPANION_BLOCK = KtStubBasedElementTypes.COMPANION_BLOCK;
    public static final IElementType ENUM_ENTRY = KtStubBasedElementTypes.ENUM_ENTRY;
    public static final IElementType CLASS_INITIALIZER = KtStubBasedElementTypes.CLASS_INITIALIZER;
    public static final IElementType SCRIPT_INITIALIZER = KtStubBasedElementTypes.SCRIPT_INITIALIZER;
    public static final IElementType SECONDARY_CONSTRUCTOR = KtStubBasedElementTypes.SECONDARY_CONSTRUCTOR;
    public static final IElementType PRIMARY_CONSTRUCTOR = KtStubBasedElementTypes.PRIMARY_CONSTRUCTOR;
    public static final IElementType CONTEXT_RECEIVER = KtStubBasedElementTypes.CONTEXT_RECEIVER;

    static {
        KtStubElementType ktStubElementType = KtStubBasedElementTypes.CONTEXT_PARAMETER_LIST;
        CONTEXT_PARAMETER_LIST = ktStubElementType;
        CONTEXT_RECEIVER_LIST = ktStubElementType;
        TYPE_PARAMETER_LIST = KtStubBasedElementTypes.TYPE_PARAMETER_LIST;
        TYPE_PARAMETER = KtStubBasedElementTypes.TYPE_PARAMETER;
        SUPER_TYPE_LIST = KtStubBasedElementTypes.SUPER_TYPE_LIST;
        DELEGATED_SUPER_TYPE_ENTRY = KtStubBasedElementTypes.DELEGATED_SUPER_TYPE_ENTRY;
        SUPER_TYPE_CALL_ENTRY = KtStubBasedElementTypes.SUPER_TYPE_CALL_ENTRY;
        SUPER_TYPE_ENTRY = KtStubBasedElementTypes.SUPER_TYPE_ENTRY;
        PROPERTY_DELEGATE = new KtNodeType("PROPERTY_DELEGATE", KtPropertyDelegate.class);
        CONSTRUCTOR_CALLEE = KtStubBasedElementTypes.CONSTRUCTOR_CALLEE;
        VALUE_PARAMETER_LIST = KtStubBasedElementTypes.VALUE_PARAMETER_LIST;
        VALUE_PARAMETER = KtStubBasedElementTypes.VALUE_PARAMETER;
        CLASS_BODY = KtStubBasedElementTypes.CLASS_BODY;
        IMPORT_LIST = KtStubBasedElementTypes.IMPORT_LIST;
        FILE_ANNOTATION_LIST = KtStubBasedElementTypes.FILE_ANNOTATION_LIST;
        IMPORT_DIRECTIVE = KtStubBasedElementTypes.IMPORT_DIRECTIVE;
        IMPORT_ALIAS = KtStubBasedElementTypes.IMPORT_ALIAS;
        MODIFIER_LIST = KtStubBasedElementTypes.MODIFIER_LIST;
        ANNOTATION = KtStubBasedElementTypes.ANNOTATION;
        ANNOTATION_ENTRY = KtStubBasedElementTypes.ANNOTATION_ENTRY;
        ANNOTATION_TARGET = KtStubBasedElementTypes.ANNOTATION_TARGET;
        TYPE_ARGUMENT_LIST = KtStubBasedElementTypes.TYPE_ARGUMENT_LIST;
        VALUE_ARGUMENT_LIST = KtStubBasedElementTypes.VALUE_ARGUMENT_LIST;
        VALUE_ARGUMENT = KtStubBasedElementTypes.VALUE_ARGUMENT;
        CONTRACT_EFFECT_LIST = KtStubBasedElementTypes.CONTRACT_EFFECT_LIST;
        CONTRACT_EFFECT = KtStubBasedElementTypes.CONTRACT_EFFECT;
        LAMBDA_ARGUMENT = KtStubBasedElementTypes.LAMBDA_ARGUMENT;
        VALUE_ARGUMENT_NAME = KtStubBasedElementTypes.VALUE_ARGUMENT_NAME;
        TYPE_REFERENCE = KtStubBasedElementTypes.TYPE_REFERENCE;
        USER_TYPE = KtStubBasedElementTypes.USER_TYPE;
        DYNAMIC_TYPE = KtStubBasedElementTypes.DYNAMIC_TYPE;
        FUNCTION_TYPE = KtStubBasedElementTypes.FUNCTION_TYPE;
        FUNCTION_TYPE_RECEIVER = KtStubBasedElementTypes.FUNCTION_TYPE_RECEIVER;
        NULLABLE_TYPE = KtStubBasedElementTypes.NULLABLE_TYPE;
        INTERSECTION_TYPE = KtStubBasedElementTypes.INTERSECTION_TYPE;
        TYPE_PROJECTION = KtStubBasedElementTypes.TYPE_PROJECTION;
        PROPERTY_ACCESSOR = KtStubBasedElementTypes.PROPERTY_ACCESSOR;
        BACKING_FIELD = KtStubBasedElementTypes.BACKING_FIELD;
        INITIALIZER_LIST = KtStubBasedElementTypes.INITIALIZER_LIST;
        TYPE_CONSTRAINT_LIST = KtStubBasedElementTypes.TYPE_CONSTRAINT_LIST;
        TYPE_CONSTRAINT = KtStubBasedElementTypes.TYPE_CONSTRAINT;
        CONSTRUCTOR_DELEGATION_CALL = new KtNodeType.KtLeftBoundNodeType("CONSTRUCTOR_DELEGATION_CALL", KtConstructorDelegationCall.class);
        CONSTRUCTOR_DELEGATION_REFERENCE = new KtNodeType.KtLeftBoundNodeType("CONSTRUCTOR_DELEGATION_REFERENCE", KtConstructorDelegationReferenceExpression.class);
        NULL = KtStubBasedElementTypes.NULL;
        BOOLEAN_CONSTANT = KtStubBasedElementTypes.BOOLEAN_CONSTANT;
        FLOAT_CONSTANT = KtStubBasedElementTypes.FLOAT_CONSTANT;
        CHARACTER_CONSTANT = KtStubBasedElementTypes.CHARACTER_CONSTANT;
        INTEGER_CONSTANT = KtStubBasedElementTypes.INTEGER_CONSTANT;
        STRING_TEMPLATE = KtStubBasedElementTypes.STRING_TEMPLATE;
        LONG_STRING_TEMPLATE_ENTRY = KtStubBasedElementTypes.LONG_STRING_TEMPLATE_ENTRY;
        SHORT_STRING_TEMPLATE_ENTRY = KtStubBasedElementTypes.SHORT_STRING_TEMPLATE_ENTRY;
        LITERAL_STRING_TEMPLATE_ENTRY = KtStubBasedElementTypes.LITERAL_STRING_TEMPLATE_ENTRY;
        ESCAPE_STRING_TEMPLATE_ENTRY = KtStubBasedElementTypes.ESCAPE_STRING_TEMPLATE_ENTRY;
        STRING_INTERPOLATION_PREFIX = KtStubBasedElementTypes.STRING_INTERPOLATION_PREFIX;
        PARENTHESIZED = new KtNodeType("PARENTHESIZED", KtParenthesizedExpression.class);
        RETURN = new KtNodeType("RETURN", KtReturnExpression.class);
        THROW = new KtNodeType("THROW", KtThrowExpression.class);
        CONTINUE = new KtNodeType("CONTINUE", KtContinueExpression.class);
        BREAK = new KtNodeType("BREAK", KtBreakExpression.class);
        IF = new KtNodeType("IF", KtIfExpression.class);
        CONDITION = new KtNodeType("CONDITION", KtContainerNode.class);
        THEN = new KtNodeType("THEN", KtContainerNodeForControlStructureBody.class);
        ELSE = new KtNodeType("ELSE", KtContainerNodeForControlStructureBody.class);
        TRY = new KtNodeType("TRY", KtTryExpression.class);
        CATCH = new KtNodeType("CATCH", KtCatchClause.class);
        FINALLY = new KtNodeType("FINALLY", KtFinallySection.class);
        FOR = new KtNodeType("FOR", KtForExpression.class);
        WHILE = new KtNodeType("WHILE", KtWhileExpression.class);
        DO_WHILE = new KtNodeType("DO_WHILE", KtDoWhileExpression.class);
        LOOP_RANGE = new KtNodeType("LOOP_RANGE", KtContainerNode.class);
        BODY = new KtNodeType("BODY", KtContainerNodeForControlStructureBody.class);
        BLOCK = KtStubBasedElementTypes.BLOCK;
        LAMBDA_EXPRESSION = KtStubBasedElementTypes.LAMBDA_EXPRESSION;
        FUNCTION_LITERAL = new KtNodeType("FUNCTION_LITERAL", KtFunctionLiteral.class);
        ANNOTATED_EXPRESSION = new KtNodeType("ANNOTATED_EXPRESSION", KtAnnotatedExpression.class);
        REFERENCE_EXPRESSION = KtStubBasedElementTypes.REFERENCE_EXPRESSION;
        ENUM_ENTRY_SUPERCLASS_REFERENCE_EXPRESSION = KtStubBasedElementTypes.ENUM_ENTRY_SUPERCLASS_REFERENCE_EXPRESSION;
        OPERATION_REFERENCE = new KtNodeType("OPERATION_REFERENCE", KtOperationReferenceExpression.class);
        LABEL = new KtNodeType("LABEL", KtLabelReferenceExpression.class);
        LABEL_QUALIFIER = new KtNodeType("LABEL_QUALIFIER", KtContainerNode.class);
        THIS_EXPRESSION = new KtNodeType("THIS_EXPRESSION", KtThisExpression.class);
        SUPER_EXPRESSION = new KtNodeType("SUPER_EXPRESSION", KtSuperExpression.class);
        BINARY_EXPRESSION = new KtNodeType("BINARY_EXPRESSION", KtBinaryExpression.class);
        BINARY_WITH_TYPE = new KtNodeType("BINARY_WITH_TYPE", KtBinaryExpressionWithTypeRHS.class);
        IS_EXPRESSION = new KtNodeType("IS_EXPRESSION", KtIsExpression.class);
        PREFIX_EXPRESSION = new KtNodeType("PREFIX_EXPRESSION", KtPrefixExpression.class);
        POSTFIX_EXPRESSION = new KtNodeType("POSTFIX_EXPRESSION", KtPostfixExpression.class);
        LABELED_EXPRESSION = new KtNodeType("LABELED_EXPRESSION", KtLabeledExpression.class);
        CALL_EXPRESSION = KtStubBasedElementTypes.CALL_EXPRESSION;
        ARRAY_ACCESS_EXPRESSION = new KtNodeType("ARRAY_ACCESS_EXPRESSION", KtArrayAccessExpression.class);
        INDICES = new KtNodeType("INDICES", KtContainerNode.class);
        DOT_QUALIFIED_EXPRESSION = KtStubBasedElementTypes.DOT_QUALIFIED_EXPRESSION;
        CALLABLE_REFERENCE_EXPRESSION = new KtNodeType("CALLABLE_REFERENCE_EXPRESSION", KtCallableReferenceExpression.class);
        CLASS_LITERAL_EXPRESSION = KtStubBasedElementTypes.CLASS_LITERAL_EXPRESSION;
        SAFE_ACCESS_EXPRESSION = new KtNodeType("SAFE_ACCESS_EXPRESSION", KtSafeQualifiedExpression.class);
        OBJECT_LITERAL = new KtNodeType("OBJECT_LITERAL", KtObjectLiteralExpression.class);
        WHEN = new KtNodeType("WHEN", KtWhenExpression.class);
        WHEN_ENTRY = new KtNodeType("WHEN_ENTRY", KtWhenEntry.class);
        WHEN_ENTRY_GUARD = new KtNodeType("WHEN_ENTRY_GUARD", KtWhenEntryGuard.class);
        WHEN_CONDITION_IN_RANGE = new KtNodeType("WHEN_CONDITION_IN_RANGE", KtWhenConditionInRange.class);
        WHEN_CONDITION_IS_PATTERN = new KtNodeType("WHEN_CONDITION_IS_PATTERN", KtWhenConditionIsPattern.class);
        WHEN_CONDITION_EXPRESSION = new KtNodeType("WHEN_CONDITION_WITH_EXPRESSION", KtWhenConditionWithExpression.class);
        COLLECTION_LITERAL_EXPRESSION = KtStubBasedElementTypes.COLLECTION_LITERAL_EXPRESSION;
        PACKAGE_DIRECTIVE = KtStubBasedElementTypes.PACKAGE_DIRECTIVE;
        SCRIPT = KtStubBasedElementTypes.SCRIPT;
        TYPE_CODE_FRAGMENT = KtStubBasedElementTypes.TYPE_CODE_FRAGMENT;
        EXPRESSION_CODE_FRAGMENT = KtStubBasedElementTypes.EXPRESSION_CODE_FRAGMENT;
        BLOCK_CODE_FRAGMENT = KtStubBasedElementTypes.BLOCK_CODE_FRAGMENT;
    }
}
