package com.iqoocg.nm;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class anim {
        public static final int dialog_enter = 0x7f060000;
        public static final int dialog_exit = 0x7f060001;
    }

    public static final class color {
        public static final int colorPrimaryDark = 0x7f010000;
        public static final int A = 0x7f010001;
        public static final int B = 0x7f010002;
        public static final int C = 0x7f010003;
        public static final int D = 0x7f010004;
        public static final int E = 0x7f010005;
        public static final int F = 0x7f010006;
        public static final int G = 0x7f010007;
        public static final int H = 0x7f010008;
    }

    public static final class drawable {
        public static final int shier = 0x7f020000;
        public static final int W = 0x7f020001;
        public static final int Rounded_Corner = 0x7f020002;
        public static final int ic_notifications = 0x7f020003;
        public static final int circle_gray_bg = 0x7f020004;
        public static final int ic_restore = 0x7f020005;
        public static final int ic_settings = 0x7f020006;
        public static final int ic_info_outline = 0x7f020007;
        public static final int Back = 0x7f020008;
        public static final int circle_gray_bg1 = 0x7f020009;
        public static final int aaaaa = 0x7f02000a;
        public static final int ___res_0x7f02000b = 0x7f02000b;
        public static final int _11__res_0x7f02000c = 0x7f02000c;
        public static final int switch_thumb_ios = 0x7f02000d;
        public static final int switch_track_ios = 0x7f02000e;
        public static final int Arrow = 0x7f02000f;
        public static final int ___res_0x7f020010 = 0x7f020010;
    }

    public static final class id {
        public static final int a = 0x7f030000;
        public static final int FPS = 0x7f030001;
        public static final int _1_res_0x7f030002 = 0x7f030002;
        public static final int _2_res_0x7f030003 = 0x7f030003;
        public static final int _3_res_0x7f030004 = 0x7f030004;
        public static final int _4_res_0x7f030005 = 0x7f030005;
        public static final int _5_res_0x7f030006 = 0x7f030006;
        public static final int _6_res_0x7f030007 = 0x7f030007;
        public static final int _7_res_0x7f030008 = 0x7f030008;
        public static final int _8_res_0x7f030009 = 0x7f030009;
        public static final int _9_res_0x7f03000a = 0x7f03000a;
        public static final int _10_res_0x7f03000b = 0x7f03000b;
        public static final int _11_res_0x7f03000c = 0x7f03000c;
        public static final int _12_res_0x7f03000d = 0x7f03000d;
        public static final int _13_res_0x7f03000e = 0x7f03000e;
        public static final int _14_res_0x7f03000f = 0x7f03000f;
        public static final int _15_res_0x7f030010 = 0x7f030010;
        public static final int _16_res_0x7f030011 = 0x7f030011;
        public static final int _17_res_0x7f030012 = 0x7f030012;
        public static final int _18_res_0x7f030013 = 0x7f030013;
    }

    public static final class layout {
        public static final int activity_main = 0x7f040000;
        public static final int activity_about_author = 0x7f040001;
        public static final int activationtool = 0x7f040002;
    }

    public static final class style {
        public static final int AppTheme = 0x7f050000;
        public static final int DialogAnimation = 0x7f050001;
    }
}
