package com.sun.tools.classfile;

import com.sun.jna.platform.win32.WinError;
import com.sun.jna.platform.win32.WinNT;
import com.sun.jna.platform.win32.WinUser;
import com.sun.jna.platform.win32.Winspool;
import com.sun.org.apache.bcel.internal.Const;
import com.sun.tools.javac.jvm.ByteCodes;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'LDC_W' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:485)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:399)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByWrappedInsn(EnumVisitor.java:364)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:349)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:284)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInvoke(EnumVisitor.java:315)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:288)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:153)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:102)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX INFO: loaded from: /workspace/dex_all/classes7.dex */
public final class Opcode {
    private static final /* synthetic */ Opcode[] $VALUES;
    public static final Opcode AALOAD;
    public static final Opcode AASTORE;
    public static final Opcode ALOAD;
    public static final Opcode ALOAD_0;
    public static final Opcode ALOAD_1;
    public static final Opcode ALOAD_2;
    public static final Opcode ALOAD_3;
    public static final Opcode ALOAD_W;
    public static final Opcode ANEWARRAY;
    public static final Opcode ARETURN;
    public static final Opcode ARRAYLENGTH;
    public static final Opcode ASTORE;
    public static final Opcode ASTORE_0;
    public static final Opcode ASTORE_1;
    public static final Opcode ASTORE_2;
    public static final Opcode ASTORE_3;
    public static final Opcode ASTORE_W;
    public static final Opcode ATHROW;
    public static final Opcode BALOAD;
    public static final Opcode BASTORE;
    public static final Opcode CACHE_FLUSH;
    public static final Opcode CALOAD;
    public static final Opcode CASTORE;
    public static final Opcode CHECKCAST;
    public static final Opcode D2F;
    public static final Opcode D2I;
    public static final Opcode D2L;
    public static final Opcode DADD;
    public static final Opcode DALOAD;
    public static final Opcode DASTORE;
    public static final Opcode DCMPG;
    public static final Opcode DCMPL;
    public static final Opcode DDIV;
    public static final Opcode DLOAD;
    public static final Opcode DLOAD_0;
    public static final Opcode DLOAD_1;
    public static final Opcode DLOAD_2;
    public static final Opcode DLOAD_3;
    public static final Opcode DLOAD_W;
    public static final Opcode DMUL;
    public static final Opcode DNEG;
    public static final Opcode DREM;
    public static final Opcode DRETURN;
    public static final Opcode DSTORE;
    public static final Opcode DSTORE_0;
    public static final Opcode DSTORE_1;
    public static final Opcode DSTORE_2;
    public static final Opcode DSTORE_3;
    public static final Opcode DSTORE_W;
    public static final Opcode DSUB;
    public static final Opcode DUP;
    public static final Opcode DUP2;
    public static final Opcode DUP2_X1;
    public static final Opcode DUP2_X2;
    public static final Opcode DUP_X1;
    public static final Opcode DUP_X2;
    public static final Opcode ENTER_SYNC_METHOD;
    public static final Opcode F2D;
    public static final Opcode F2I;
    public static final Opcode F2L;
    public static final Opcode FADD;
    public static final Opcode FALOAD;
    public static final Opcode FASTORE;
    public static final Opcode FCMPG;
    public static final Opcode FCMPL;
    public static final Opcode FDIV;
    public static final Opcode FLOAD;
    public static final Opcode FLOAD_0;
    public static final Opcode FLOAD_1;
    public static final Opcode FLOAD_2;
    public static final Opcode FLOAD_3;
    public static final Opcode FLOAD_W;
    public static final Opcode FMUL;
    public static final Opcode FNEG;
    public static final Opcode FREM;
    public static final Opcode FRETURN;
    public static final Opcode FSTORE;
    public static final Opcode FSTORE_0;
    public static final Opcode FSTORE_1;
    public static final Opcode FSTORE_2;
    public static final Opcode FSTORE_3;
    public static final Opcode FSTORE_W;
    public static final Opcode FSUB;
    public static final Opcode GETFIELD;
    public static final Opcode GETSTATIC;
    public static final Opcode GOTO;
    public static final Opcode GOTO_W;
    public static final Opcode I2B;
    public static final Opcode I2C;
    public static final Opcode I2D;
    public static final Opcode I2F;
    public static final Opcode I2L;
    public static final Opcode I2S;
    public static final Opcode IADD;
    public static final Opcode IALOAD;
    public static final Opcode IAND;
    public static final Opcode IASTORE;
    public static final Opcode IDIV;
    public static final Opcode IFEQ;
    public static final Opcode IFGE;
    public static final Opcode IFGT;
    public static final Opcode IFLE;
    public static final Opcode IFLT;
    public static final Opcode IFNE;
    public static final Opcode IFNONNULL;
    public static final Opcode IFNULL;
    public static final Opcode IF_ACMPEQ;
    public static final Opcode IF_ACMPNE;
    public static final Opcode IF_ICMPEQ;
    public static final Opcode IF_ICMPGE;
    public static final Opcode IF_ICMPGT;
    public static final Opcode IF_ICMPLE;
    public static final Opcode IF_ICMPLT;
    public static final Opcode IF_ICMPNE;
    public static final Opcode IINC;
    public static final Opcode IINC_W;
    public static final Opcode ILOAD;
    public static final Opcode ILOAD_0;
    public static final Opcode ILOAD_1;
    public static final Opcode ILOAD_2;
    public static final Opcode ILOAD_3;
    public static final Opcode ILOAD_W;
    public static final Opcode IMUL;
    public static final Opcode INEG;
    public static final Opcode INSTANCEOF;
    public static final Opcode INVOKEDYNAMIC;
    public static final Opcode INVOKEINTERFACE;
    public static final Opcode INVOKESPECIAL;
    public static final Opcode INVOKESTATIC;
    public static final Opcode INVOKEVIRTUAL;
    public static final Opcode IOR;
    public static final Opcode IREM;
    public static final Opcode IRETURN;
    public static final Opcode ISHL;
    public static final Opcode ISHR;
    public static final Opcode ISTORE;
    public static final Opcode ISTORE_0;
    public static final Opcode ISTORE_1;
    public static final Opcode ISTORE_2;
    public static final Opcode ISTORE_3;
    public static final Opcode ISTORE_W;
    public static final Opcode ISUB;
    public static final Opcode IUSHR;
    public static final Opcode IXOR;
    public static final Opcode JSR;
    public static final Opcode JSR_W;
    public static final Opcode L2D;
    public static final Opcode L2F;
    public static final Opcode L2I;
    public static final Opcode LADD;
    public static final Opcode LALOAD;
    public static final Opcode LAND;
    public static final Opcode LASTORE;
    public static final Opcode LCMP;
    public static final Opcode LDC2_W;
    public static final Opcode LDC_W;
    public static final Opcode LDIV;
    public static final Opcode LLOAD;
    public static final Opcode LLOAD_0;
    public static final Opcode LLOAD_1;
    public static final Opcode LLOAD_2;
    public static final Opcode LLOAD_3;
    public static final Opcode LLOAD_W;
    public static final Opcode LMUL;
    public static final Opcode LNEG;
    public static final Opcode LOAD_BYTE;
    public static final Opcode LOAD_CHAR;
    public static final Opcode LOAD_CHAR_OE;
    public static final Opcode LOAD_SHORT;
    public static final Opcode LOAD_SHORT_OE;
    public static final Opcode LOAD_UBYTE;
    public static final Opcode LOAD_WORD;
    public static final Opcode LOAD_WORD_OE;
    public static final Opcode LOOKUPSWITCH;
    public static final Opcode LOR;
    public static final Opcode LREM;
    public static final Opcode LRETURN;
    public static final Opcode LSHL;
    public static final Opcode LSHR;
    public static final Opcode LSTORE;
    public static final Opcode LSTORE_0;
    public static final Opcode LSTORE_1;
    public static final Opcode LSTORE_2;
    public static final Opcode LSTORE_3;
    public static final Opcode LSTORE_W;
    public static final Opcode LSUB;
    public static final Opcode LUSHR;
    public static final Opcode LXOR;
    public static final Opcode MONITORENTER;
    public static final Opcode MONITOREXIT;
    public static final Opcode MULTIANEWARRAY;
    public static final Opcode NCLOAD_BYTE;
    public static final Opcode NCLOAD_CHAR;
    public static final Opcode NCLOAD_CHAR_OE;
    public static final Opcode NCLOAD_SHORT;
    public static final Opcode NCLOAD_SHORT_OE;
    public static final Opcode NCLOAD_UBYTE;
    public static final Opcode NCLOAD_WORD;
    public static final Opcode NCLOAD_WORD_OE;
    public static final Opcode NCSTORE_BYTE;
    public static final Opcode NCSTORE_SHORT;
    public static final Opcode NCSTORE_SHORT_OE;
    public static final Opcode NCSTORE_WORD;
    public static final Opcode NCSTORE_WORD_OE;
    public static final Opcode NEW;
    public static final Opcode NEWARRAY;
    public static final int NONPRIV = 254;
    public static final Opcode POP;
    public static final Opcode POP2;
    public static final int PRIV = 255;
    public static final Opcode PRIV_CACHE_FLUSH;
    public static final Opcode PRIV_CACHE_INDEX_FLUSH;
    public static final Opcode PRIV_LOAD_BYTE;
    public static final Opcode PRIV_LOAD_CHAR;
    public static final Opcode PRIV_LOAD_CHAR_OE;
    public static final Opcode PRIV_LOAD_SHORT;
    public static final Opcode PRIV_LOAD_SHORT_OE;
    public static final Opcode PRIV_LOAD_UBYTE;
    public static final Opcode PRIV_LOAD_WORD;
    public static final Opcode PRIV_LOAD_WORD_OE;
    public static final Opcode PRIV_NCLOAD_BYTE;
    public static final Opcode PRIV_NCLOAD_CHAR;
    public static final Opcode PRIV_NCLOAD_CHAR_OE;
    public static final Opcode PRIV_NCLOAD_SHORT;
    public static final Opcode PRIV_NCLOAD_SHORT_OE;
    public static final Opcode PRIV_NCLOAD_UBYTE;
    public static final Opcode PRIV_NCLOAD_WORD;
    public static final Opcode PRIV_NCLOAD_WORD_OE;
    public static final Opcode PRIV_NCSTORE_BYTE;
    public static final Opcode PRIV_NCSTORE_SHORT;
    public static final Opcode PRIV_NCSTORE_SHORT_OE;
    public static final Opcode PRIV_NCSTORE_WORD;
    public static final Opcode PRIV_NCSTORE_WORD_OE;
    public static final Opcode PRIV_POWERDOWN;
    public static final Opcode PRIV_READ_DCACHE_DATA;
    public static final Opcode PRIV_READ_DCACHE_TAG;
    public static final Opcode PRIV_READ_ICACHE_DATA;
    public static final Opcode PRIV_READ_ICACHE_TAG;
    public static final Opcode PRIV_READ_REG_0;
    public static final Opcode PRIV_READ_REG_1;
    public static final Opcode PRIV_READ_REG_10;
    public static final Opcode PRIV_READ_REG_11;
    public static final Opcode PRIV_READ_REG_12;
    public static final Opcode PRIV_READ_REG_13;
    public static final Opcode PRIV_READ_REG_14;
    public static final Opcode PRIV_READ_REG_15;
    public static final Opcode PRIV_READ_REG_16;
    public static final Opcode PRIV_READ_REG_17;
    public static final Opcode PRIV_READ_REG_18;
    public static final Opcode PRIV_READ_REG_19;
    public static final Opcode PRIV_READ_REG_2;
    public static final Opcode PRIV_READ_REG_20;
    public static final Opcode PRIV_READ_REG_21;
    public static final Opcode PRIV_READ_REG_22;
    public static final Opcode PRIV_READ_REG_23;
    public static final Opcode PRIV_READ_REG_24;
    public static final Opcode PRIV_READ_REG_25;
    public static final Opcode PRIV_READ_REG_26;
    public static final Opcode PRIV_READ_REG_27;
    public static final Opcode PRIV_READ_REG_28;
    public static final Opcode PRIV_READ_REG_29;
    public static final Opcode PRIV_READ_REG_3;
    public static final Opcode PRIV_READ_REG_30;
    public static final Opcode PRIV_READ_REG_31;
    public static final Opcode PRIV_READ_REG_4;
    public static final Opcode PRIV_READ_REG_5;
    public static final Opcode PRIV_READ_REG_6;
    public static final Opcode PRIV_READ_REG_7;
    public static final Opcode PRIV_READ_REG_8;
    public static final Opcode PRIV_READ_REG_9;
    public static final Opcode PRIV_READ_SCACHE_DATA;
    public static final Opcode PRIV_RESET;
    public static final Opcode PRIV_RET_FROM_TRAP;
    public static final Opcode PRIV_STORE_BYTE;
    public static final Opcode PRIV_STORE_SHORT;
    public static final Opcode PRIV_STORE_SHORT_OE;
    public static final Opcode PRIV_STORE_WORD;
    public static final Opcode PRIV_STORE_WORD_OE;
    public static final Opcode PRIV_WRITE_DCACHE_DATA;
    public static final Opcode PRIV_WRITE_DCACHE_TAG;
    public static final Opcode PRIV_WRITE_ICACHE_DATA;
    public static final Opcode PRIV_WRITE_ICACHE_TAG;
    public static final Opcode PRIV_WRITE_REG_0;
    public static final Opcode PRIV_WRITE_REG_1;
    public static final Opcode PRIV_WRITE_REG_10;
    public static final Opcode PRIV_WRITE_REG_11;
    public static final Opcode PRIV_WRITE_REG_12;
    public static final Opcode PRIV_WRITE_REG_13;
    public static final Opcode PRIV_WRITE_REG_14;
    public static final Opcode PRIV_WRITE_REG_15;
    public static final Opcode PRIV_WRITE_REG_16;
    public static final Opcode PRIV_WRITE_REG_17;
    public static final Opcode PRIV_WRITE_REG_18;
    public static final Opcode PRIV_WRITE_REG_19;
    public static final Opcode PRIV_WRITE_REG_2;
    public static final Opcode PRIV_WRITE_REG_20;
    public static final Opcode PRIV_WRITE_REG_21;
    public static final Opcode PRIV_WRITE_REG_22;
    public static final Opcode PRIV_WRITE_REG_23;
    public static final Opcode PRIV_WRITE_REG_24;
    public static final Opcode PRIV_WRITE_REG_25;
    public static final Opcode PRIV_WRITE_REG_26;
    public static final Opcode PRIV_WRITE_REG_27;
    public static final Opcode PRIV_WRITE_REG_28;
    public static final Opcode PRIV_WRITE_REG_29;
    public static final Opcode PRIV_WRITE_REG_3;
    public static final Opcode PRIV_WRITE_REG_30;
    public static final Opcode PRIV_WRITE_REG_31;
    public static final Opcode PRIV_WRITE_REG_4;
    public static final Opcode PRIV_WRITE_REG_5;
    public static final Opcode PRIV_WRITE_REG_6;
    public static final Opcode PRIV_WRITE_REG_7;
    public static final Opcode PRIV_WRITE_REG_8;
    public static final Opcode PRIV_WRITE_REG_9;
    public static final Opcode PRIV_WRITE_SCACHE_DATA;
    public static final Opcode PRIV_ZERO_LINE;
    public static final Opcode PUTFIELD;
    public static final Opcode PUTSTATIC;
    public static final Opcode RET;
    public static final Opcode RETURN;
    public static final Opcode RET_FROM_SUB;
    public static final Opcode RET_W;
    public static final Opcode SALOAD;
    public static final Opcode SASTORE;
    public static final Opcode STORE_BYTE;
    public static final Opcode STORE_SHORT;
    public static final Opcode STORE_SHORT_OE;
    public static final Opcode STORE_WORD;
    public static final Opcode STORE_WORD_OE;
    public static final Opcode SWAP;
    public static final Opcode TABLESWITCH;
    public static final int WIDE = 196;
    public static final Opcode ZERO_LINE;
    private static final Opcode[] nonPrivOpcodes;
    private static final Opcode[] privOpcodes;
    private static final Opcode[] stdOpcodes;
    private static final Opcode[] wideOpcodes;
    public final Instruction.Kind kind;
    public final int opcode;
    public final Set set;
    public static final Opcode NOP = new Opcode("NOP", 0, 0);
    public static final Opcode ACONST_NULL = new Opcode("ACONST_NULL", 1, 1);
    public static final Opcode ICONST_M1 = new Opcode("ICONST_M1", 2, 2);
    public static final Opcode ICONST_0 = new Opcode("ICONST_0", 3, 3);
    public static final Opcode ICONST_1 = new Opcode("ICONST_1", 4, 4);
    public static final Opcode ICONST_2 = new Opcode("ICONST_2", 5, 5);
    public static final Opcode ICONST_3 = new Opcode("ICONST_3", 6, 6);
    public static final Opcode ICONST_4 = new Opcode("ICONST_4", 7, 7);
    public static final Opcode ICONST_5 = new Opcode("ICONST_5", 8, 8);
    public static final Opcode LCONST_0 = new Opcode("LCONST_0", 9, 9);
    public static final Opcode LCONST_1 = new Opcode("LCONST_1", 10, 10);
    public static final Opcode FCONST_0 = new Opcode("FCONST_0", 11, 11);
    public static final Opcode FCONST_1 = new Opcode("FCONST_1", 12, 12);
    public static final Opcode FCONST_2 = new Opcode("FCONST_2", 13, 13);
    public static final Opcode DCONST_0 = new Opcode("DCONST_0", 14, 14);
    public static final Opcode DCONST_1 = new Opcode("DCONST_1", 15, 15);
    public static final Opcode BIPUSH = new Opcode("BIPUSH", 16, 16, Instruction.Kind.BYTE);
    public static final Opcode SIPUSH = new Opcode("SIPUSH", 17, 17, Instruction.Kind.SHORT);
    public static final Opcode LDC = new Opcode("LDC", 18, 18, Instruction.Kind.CPREF);

    public enum Set {
        STANDARD,
        PICOJAVA
    }

    private static /* synthetic */ Opcode[] $values() {
        return new Opcode[]{NOP, ACONST_NULL, ICONST_M1, ICONST_0, ICONST_1, ICONST_2, ICONST_3, ICONST_4, ICONST_5, LCONST_0, LCONST_1, FCONST_0, FCONST_1, FCONST_2, DCONST_0, DCONST_1, BIPUSH, SIPUSH, LDC, LDC_W, LDC2_W, ILOAD, LLOAD, FLOAD, DLOAD, ALOAD, ILOAD_0, ILOAD_1, ILOAD_2, ILOAD_3, LLOAD_0, LLOAD_1, LLOAD_2, LLOAD_3, FLOAD_0, FLOAD_1, FLOAD_2, FLOAD_3, DLOAD_0, DLOAD_1, DLOAD_2, DLOAD_3, ALOAD_0, ALOAD_1, ALOAD_2, ALOAD_3, IALOAD, LALOAD, FALOAD, DALOAD, AALOAD, BALOAD, CALOAD, SALOAD, ISTORE, LSTORE, FSTORE, DSTORE, ASTORE, ISTORE_0, ISTORE_1, ISTORE_2, ISTORE_3, LSTORE_0, LSTORE_1, LSTORE_2, LSTORE_3, FSTORE_0, FSTORE_1, FSTORE_2, FSTORE_3, DSTORE_0, DSTORE_1, DSTORE_2, DSTORE_3, ASTORE_0, ASTORE_1, ASTORE_2, ASTORE_3, IASTORE, LASTORE, FASTORE, DASTORE, AASTORE, BASTORE, CASTORE, SASTORE, POP, POP2, DUP, DUP_X1, DUP_X2, DUP2, DUP2_X1, DUP2_X2, SWAP, IADD, LADD, FADD, DADD, ISUB, LSUB, FSUB, DSUB, IMUL, LMUL, FMUL, DMUL, IDIV, LDIV, FDIV, DDIV, IREM, LREM, FREM, DREM, INEG, LNEG, FNEG, DNEG, ISHL, LSHL, ISHR, LSHR, IUSHR, LUSHR, IAND, LAND, IOR, LOR, IXOR, LXOR, IINC, I2L, I2F, I2D, L2I, L2F, L2D, F2I, F2L, F2D, D2I, D2L, D2F, I2B, I2C, I2S, LCMP, FCMPL, FCMPG, DCMPL, DCMPG, IFEQ, IFNE, IFLT, IFGE, IFGT, IFLE, IF_ICMPEQ, IF_ICMPNE, IF_ICMPLT, IF_ICMPGE, IF_ICMPGT, IF_ICMPLE, IF_ACMPEQ, IF_ACMPNE, GOTO, JSR, RET, TABLESWITCH, LOOKUPSWITCH, IRETURN, LRETURN, FRETURN, DRETURN, ARETURN, RETURN, GETSTATIC, PUTSTATIC, GETFIELD, PUTFIELD, INVOKEVIRTUAL, INVOKESPECIAL, INVOKESTATIC, INVOKEINTERFACE, INVOKEDYNAMIC, NEW, NEWARRAY, ANEWARRAY, ARRAYLENGTH, ATHROW, CHECKCAST, INSTANCEOF, MONITORENTER, MONITOREXIT, MULTIANEWARRAY, IFNULL, IFNONNULL, GOTO_W, JSR_W, ILOAD_W, LLOAD_W, FLOAD_W, DLOAD_W, ALOAD_W, ISTORE_W, LSTORE_W, FSTORE_W, DSTORE_W, ASTORE_W, IINC_W, RET_W, LOAD_UBYTE, LOAD_BYTE, LOAD_CHAR, LOAD_SHORT, LOAD_WORD, RET_FROM_SUB, LOAD_CHAR_OE, LOAD_SHORT_OE, LOAD_WORD_OE, NCLOAD_UBYTE, NCLOAD_BYTE, NCLOAD_CHAR, NCLOAD_SHORT, NCLOAD_WORD, NCLOAD_CHAR_OE, NCLOAD_SHORT_OE, NCLOAD_WORD_OE, CACHE_FLUSH, STORE_BYTE, STORE_SHORT, STORE_WORD, STORE_SHORT_OE, STORE_WORD_OE, NCSTORE_BYTE, NCSTORE_SHORT, NCSTORE_WORD, NCSTORE_SHORT_OE, NCSTORE_WORD_OE, ZERO_LINE, ENTER_SYNC_METHOD, PRIV_LOAD_UBYTE, PRIV_LOAD_BYTE, PRIV_LOAD_CHAR, PRIV_LOAD_SHORT, PRIV_LOAD_WORD, PRIV_RET_FROM_TRAP, PRIV_READ_DCACHE_TAG, PRIV_READ_DCACHE_DATA, PRIV_LOAD_CHAR_OE, PRIV_LOAD_SHORT_OE, PRIV_LOAD_WORD_OE, PRIV_READ_ICACHE_TAG, PRIV_READ_ICACHE_DATA, PRIV_NCLOAD_UBYTE, PRIV_NCLOAD_BYTE, PRIV_NCLOAD_CHAR, PRIV_NCLOAD_SHORT, PRIV_NCLOAD_WORD, PRIV_POWERDOWN, PRIV_READ_SCACHE_DATA, PRIV_NCLOAD_CHAR_OE, PRIV_NCLOAD_SHORT_OE, PRIV_NCLOAD_WORD_OE, PRIV_CACHE_FLUSH, PRIV_CACHE_INDEX_FLUSH, PRIV_STORE_BYTE, PRIV_STORE_SHORT, PRIV_STORE_WORD, PRIV_WRITE_DCACHE_TAG, PRIV_WRITE_DCACHE_DATA, PRIV_STORE_SHORT_OE, PRIV_STORE_WORD_OE, PRIV_WRITE_ICACHE_TAG, PRIV_WRITE_ICACHE_DATA, PRIV_NCSTORE_BYTE, PRIV_NCSTORE_SHORT, PRIV_NCSTORE_WORD, PRIV_RESET, PRIV_WRITE_SCACHE_DATA, PRIV_NCSTORE_SHORT_OE, PRIV_NCSTORE_WORD_OE, PRIV_ZERO_LINE, PRIV_READ_REG_0, PRIV_READ_REG_1, PRIV_READ_REG_2, PRIV_READ_REG_3, PRIV_READ_REG_4, PRIV_READ_REG_5, PRIV_READ_REG_6, PRIV_READ_REG_7, PRIV_READ_REG_8, PRIV_READ_REG_9, PRIV_READ_REG_10, PRIV_READ_REG_11, PRIV_READ_REG_12, PRIV_READ_REG_13, PRIV_READ_REG_14, PRIV_READ_REG_15, PRIV_READ_REG_16, PRIV_READ_REG_17, PRIV_READ_REG_18, PRIV_READ_REG_19, PRIV_READ_REG_20, PRIV_READ_REG_21, PRIV_READ_REG_22, PRIV_READ_REG_23, PRIV_READ_REG_24, PRIV_READ_REG_25, PRIV_READ_REG_26, PRIV_READ_REG_27, PRIV_READ_REG_28, PRIV_READ_REG_29, PRIV_READ_REG_30, PRIV_READ_REG_31, PRIV_WRITE_REG_0, PRIV_WRITE_REG_1, PRIV_WRITE_REG_2, PRIV_WRITE_REG_3, PRIV_WRITE_REG_4, PRIV_WRITE_REG_5, PRIV_WRITE_REG_6, PRIV_WRITE_REG_7, PRIV_WRITE_REG_8, PRIV_WRITE_REG_9, PRIV_WRITE_REG_10, PRIV_WRITE_REG_11, PRIV_WRITE_REG_12, PRIV_WRITE_REG_13, PRIV_WRITE_REG_14, PRIV_WRITE_REG_15, PRIV_WRITE_REG_16, PRIV_WRITE_REG_17, PRIV_WRITE_REG_18, PRIV_WRITE_REG_19, PRIV_WRITE_REG_20, PRIV_WRITE_REG_21, PRIV_WRITE_REG_22, PRIV_WRITE_REG_23, PRIV_WRITE_REG_24, PRIV_WRITE_REG_25, PRIV_WRITE_REG_26, PRIV_WRITE_REG_27, PRIV_WRITE_REG_28, PRIV_WRITE_REG_29, PRIV_WRITE_REG_30, PRIV_WRITE_REG_31};
    }

    static {
        Instruction.Kind kind = Instruction.Kind.CPREF_W;
        LDC_W = new Opcode("LDC_W", 19, 19, kind);
        LDC2_W = new Opcode("LDC2_W", 20, 20, kind);
        Instruction.Kind kind2 = Instruction.Kind.LOCAL;
        ILOAD = new Opcode("ILOAD", 21, 21, kind2);
        LLOAD = new Opcode("LLOAD", 22, 22, kind2);
        FLOAD = new Opcode("FLOAD", 23, 23, kind2);
        DLOAD = new Opcode("DLOAD", 24, 24, kind2);
        ALOAD = new Opcode("ALOAD", 25, 25, kind2);
        ILOAD_0 = new Opcode("ILOAD_0", 26, 26);
        ILOAD_1 = new Opcode("ILOAD_1", 27, 27);
        ILOAD_2 = new Opcode("ILOAD_2", 28, 28);
        ILOAD_3 = new Opcode("ILOAD_3", 29, 29);
        LLOAD_0 = new Opcode("LLOAD_0", 30, 30);
        LLOAD_1 = new Opcode("LLOAD_1", 31, 31);
        LLOAD_2 = new Opcode("LLOAD_2", 32, 32);
        LLOAD_3 = new Opcode("LLOAD_3", 33, 33);
        FLOAD_0 = new Opcode("FLOAD_0", 34, 34);
        FLOAD_1 = new Opcode("FLOAD_1", 35, 35);
        FLOAD_2 = new Opcode("FLOAD_2", 36, 36);
        FLOAD_3 = new Opcode("FLOAD_3", 37, 37);
        DLOAD_0 = new Opcode("DLOAD_0", 38, 38);
        DLOAD_1 = new Opcode("DLOAD_1", 39, 39);
        DLOAD_2 = new Opcode("DLOAD_2", 40, 40);
        DLOAD_3 = new Opcode("DLOAD_3", 41, 41);
        ALOAD_0 = new Opcode("ALOAD_0", 42, 42);
        ALOAD_1 = new Opcode("ALOAD_1", 43, 43);
        ALOAD_2 = new Opcode("ALOAD_2", 44, 44);
        ALOAD_3 = new Opcode("ALOAD_3", 45, 45);
        IALOAD = new Opcode("IALOAD", 46, 46);
        LALOAD = new Opcode("LALOAD", 47, 47);
        FALOAD = new Opcode("FALOAD", 48, 48);
        DALOAD = new Opcode("DALOAD", 49, 49);
        AALOAD = new Opcode("AALOAD", 50, 50);
        BALOAD = new Opcode("BALOAD", 51, 51);
        CALOAD = new Opcode("CALOAD", 52, 52);
        SALOAD = new Opcode("SALOAD", 53, 53);
        ISTORE = new Opcode("ISTORE", 54, 54, kind2);
        LSTORE = new Opcode("LSTORE", 55, 55, kind2);
        FSTORE = new Opcode("FSTORE", 56, 56, kind2);
        DSTORE = new Opcode("DSTORE", 57, 57, kind2);
        ASTORE = new Opcode("ASTORE", 58, 58, kind2);
        ISTORE_0 = new Opcode("ISTORE_0", 59, 59);
        ISTORE_1 = new Opcode("ISTORE_1", 60, 60);
        ISTORE_2 = new Opcode("ISTORE_2", 61, 61);
        ISTORE_3 = new Opcode("ISTORE_3", 62, 62);
        LSTORE_0 = new Opcode("LSTORE_0", 63, 63);
        LSTORE_1 = new Opcode("LSTORE_1", 64, 64);
        LSTORE_2 = new Opcode("LSTORE_2", 65, 65);
        LSTORE_3 = new Opcode("LSTORE_3", 66, 66);
        FSTORE_0 = new Opcode("FSTORE_0", 67, 67);
        FSTORE_1 = new Opcode("FSTORE_1", 68, 68);
        FSTORE_2 = new Opcode("FSTORE_2", 69, 69);
        FSTORE_3 = new Opcode("FSTORE_3", 70, 70);
        DSTORE_0 = new Opcode("DSTORE_0", 71, 71);
        DSTORE_1 = new Opcode("DSTORE_1", 72, 72);
        DSTORE_2 = new Opcode("DSTORE_2", 73, 73);
        DSTORE_3 = new Opcode("DSTORE_3", 74, 74);
        ASTORE_0 = new Opcode("ASTORE_0", 75, 75);
        ASTORE_1 = new Opcode("ASTORE_1", 76, 76);
        ASTORE_2 = new Opcode("ASTORE_2", 77, 77);
        ASTORE_3 = new Opcode("ASTORE_3", 78, 78);
        IASTORE = new Opcode("IASTORE", 79, 79);
        LASTORE = new Opcode("LASTORE", 80, 80);
        FASTORE = new Opcode("FASTORE", 81, 81);
        DASTORE = new Opcode("DASTORE", 82, 82);
        AASTORE = new Opcode("AASTORE", 83, 83);
        BASTORE = new Opcode("BASTORE", 84, 84);
        CASTORE = new Opcode("CASTORE", 85, 85);
        SASTORE = new Opcode("SASTORE", 86, 86);
        POP = new Opcode("POP", 87, 87);
        POP2 = new Opcode("POP2", 88, 88);
        DUP = new Opcode("DUP", 89, 89);
        DUP_X1 = new Opcode("DUP_X1", 90, 90);
        DUP_X2 = new Opcode("DUP_X2", 91, 91);
        DUP2 = new Opcode("DUP2", 92, 92);
        DUP2_X1 = new Opcode("DUP2_X1", 93, 93);
        DUP2_X2 = new Opcode("DUP2_X2", 94, 94);
        SWAP = new Opcode("SWAP", 95, 95);
        IADD = new Opcode("IADD", 96, 96);
        LADD = new Opcode("LADD", 97, 97);
        FADD = new Opcode("FADD", 98, 98);
        DADD = new Opcode("DADD", 99, 99);
        ISUB = new Opcode("ISUB", 100, 100);
        LSUB = new Opcode("LSUB", 101, 101);
        FSUB = new Opcode("FSUB", 102, 102);
        DSUB = new Opcode("DSUB", 103, 103);
        IMUL = new Opcode("IMUL", 104, 104);
        LMUL = new Opcode("LMUL", 105, 105);
        FMUL = new Opcode("FMUL", 106, 106);
        DMUL = new Opcode("DMUL", 107, 107);
        IDIV = new Opcode("IDIV", 108, 108);
        LDIV = new Opcode("LDIV", 109, 109);
        FDIV = new Opcode("FDIV", 110, 110);
        DDIV = new Opcode("DDIV", 111, 111);
        IREM = new Opcode("IREM", 112, 112);
        LREM = new Opcode("LREM", 113, 113);
        FREM = new Opcode("FREM", 114, 114);
        DREM = new Opcode("DREM", 115, 115);
        INEG = new Opcode("INEG", 116, 116);
        LNEG = new Opcode("LNEG", 117, 117);
        FNEG = new Opcode("FNEG", 118, 118);
        DNEG = new Opcode("DNEG", 119, 119);
        ISHL = new Opcode("ISHL", 120, 120);
        LSHL = new Opcode("LSHL", 121, 121);
        ISHR = new Opcode("ISHR", 122, 122);
        LSHR = new Opcode("LSHR", 123, 123);
        IUSHR = new Opcode("IUSHR", 124, 124);
        LUSHR = new Opcode("LUSHR", 125, 125);
        IAND = new Opcode("IAND", 126, 126);
        LAND = new Opcode("LAND", 127, 127);
        IOR = new Opcode("IOR", 128, 128);
        LOR = new Opcode("LOR", 129, 129);
        IXOR = new Opcode("IXOR", 130, 130);
        LXOR = new Opcode("LXOR", 131, 131);
        IINC = new Opcode("IINC", 132, 132, Instruction.Kind.LOCAL_BYTE);
        I2L = new Opcode("I2L", 133, 133);
        I2F = new Opcode("I2F", 134, 134);
        I2D = new Opcode("I2D", 135, 135);
        L2I = new Opcode("L2I", 136, 136);
        L2F = new Opcode("L2F", 137, 137);
        L2D = new Opcode("L2D", 138, 138);
        F2I = new Opcode("F2I", 139, 139);
        F2L = new Opcode("F2L", 140, 140);
        F2D = new Opcode("F2D", 141, 141);
        D2I = new Opcode("D2I", 142, 142);
        D2L = new Opcode("D2L", 143, 143);
        D2F = new Opcode("D2F", 144, 144);
        I2B = new Opcode("I2B", 145, 145);
        I2C = new Opcode("I2C", 146, 146);
        I2S = new Opcode("I2S", 147, 147);
        LCMP = new Opcode("LCMP", 148, 148);
        FCMPL = new Opcode("FCMPL", 149, 149);
        FCMPG = new Opcode("FCMPG", 150, 150);
        DCMPL = new Opcode("DCMPL", 151, 151);
        DCMPG = new Opcode("DCMPG", 152, 152);
        Instruction.Kind kind3 = Instruction.Kind.BRANCH;
        IFEQ = new Opcode("IFEQ", 153, 153, kind3);
        IFNE = new Opcode("IFNE", 154, 154, kind3);
        IFLT = new Opcode("IFLT", 155, 155, kind3);
        IFGE = new Opcode("IFGE", 156, 156, kind3);
        IFGT = new Opcode("IFGT", 157, 157, kind3);
        IFLE = new Opcode("IFLE", 158, 158, kind3);
        IF_ICMPEQ = new Opcode("IF_ICMPEQ", 159, 159, kind3);
        IF_ICMPNE = new Opcode("IF_ICMPNE", 160, 160, kind3);
        IF_ICMPLT = new Opcode("IF_ICMPLT", 161, 161, kind3);
        IF_ICMPGE = new Opcode("IF_ICMPGE", 162, 162, kind3);
        IF_ICMPGT = new Opcode("IF_ICMPGT", 163, 163, kind3);
        IF_ICMPLE = new Opcode("IF_ICMPLE", 164, 164, kind3);
        IF_ACMPEQ = new Opcode("IF_ACMPEQ", 165, 165, kind3);
        IF_ACMPNE = new Opcode("IF_ACMPNE", 166, 166, kind3);
        GOTO = new Opcode("GOTO", 167, 167, kind3);
        JSR = new Opcode("JSR", 168, 168, kind3);
        RET = new Opcode("RET", 169, 169, kind2);
        Instruction.Kind kind4 = Instruction.Kind.DYNAMIC;
        TABLESWITCH = new Opcode("TABLESWITCH", 170, 170, kind4);
        LOOKUPSWITCH = new Opcode("LOOKUPSWITCH", 171, 171, kind4);
        IRETURN = new Opcode("IRETURN", 172, 172);
        LRETURN = new Opcode("LRETURN", 173, 173);
        FRETURN = new Opcode("FRETURN", 174, 174);
        DRETURN = new Opcode("DRETURN", 175, 175);
        ARETURN = new Opcode("ARETURN", 176, 176);
        RETURN = new Opcode("RETURN", 177, 177);
        GETSTATIC = new Opcode("GETSTATIC", 178, 178, kind);
        PUTSTATIC = new Opcode("PUTSTATIC", 179, 179, kind);
        GETFIELD = new Opcode("GETFIELD", 180, 180, kind);
        PUTFIELD = new Opcode("PUTFIELD", 181, 181, kind);
        INVOKEVIRTUAL = new Opcode("INVOKEVIRTUAL", 182, 182, kind);
        INVOKESPECIAL = new Opcode("INVOKESPECIAL", 183, 183, kind);
        INVOKESTATIC = new Opcode("INVOKESTATIC", 184, 184, kind);
        Instruction.Kind kind5 = Instruction.Kind.CPREF_W_UBYTE_ZERO;
        INVOKEINTERFACE = new Opcode("INVOKEINTERFACE", 185, 185, kind5);
        INVOKEDYNAMIC = new Opcode("INVOKEDYNAMIC", 186, 186, kind5);
        NEW = new Opcode("NEW", 187, 187, kind);
        NEWARRAY = new Opcode("NEWARRAY", 188, 188, Instruction.Kind.ATYPE);
        ANEWARRAY = new Opcode("ANEWARRAY", 189, 189, kind);
        ARRAYLENGTH = new Opcode("ARRAYLENGTH", 190, 190);
        ATHROW = new Opcode("ATHROW", 191, 191);
        CHECKCAST = new Opcode("CHECKCAST", 192, 192, kind);
        INSTANCEOF = new Opcode("INSTANCEOF", 193, 193, kind);
        MONITORENTER = new Opcode("MONITORENTER", 194, 194);
        MONITOREXIT = new Opcode("MONITOREXIT", 195, 195);
        MULTIANEWARRAY = new Opcode("MULTIANEWARRAY", 196, 197, Instruction.Kind.CPREF_W_UBYTE);
        IFNULL = new Opcode("IFNULL", 197, 198, kind3);
        IFNONNULL = new Opcode("IFNONNULL", 198, 199, kind3);
        Instruction.Kind kind6 = Instruction.Kind.BRANCH_W;
        GOTO_W = new Opcode("GOTO_W", 199, 200, kind6);
        JSR_W = new Opcode("JSR_W", 200, 201, kind6);
        Instruction.Kind kind7 = Instruction.Kind.WIDE_LOCAL;
        ILOAD_W = new Opcode("ILOAD_W", 201, 50197, kind7);
        LLOAD_W = new Opcode("LLOAD_W", 202, 50198, kind7);
        FLOAD_W = new Opcode("FLOAD_W", 203, 50199, kind7);
        DLOAD_W = new Opcode("DLOAD_W", 204, 50200, kind7);
        ALOAD_W = new Opcode("ALOAD_W", WinError.ERROR_NO_SIGNAL_SENT, 50201, kind7);
        ISTORE_W = new Opcode("ISTORE_W", WinError.ERROR_FILENAME_EXCED_RANGE, 50230, kind7);
        LSTORE_W = new Opcode("LSTORE_W", WinError.ERROR_RING2_STACK_IN_USE, 50231, kind7);
        FSTORE_W = new Opcode("FSTORE_W", WinError.ERROR_META_EXPANSION_TOO_LONG, 50232, kind7);
        DSTORE_W = new Opcode("DSTORE_W", WinError.ERROR_INVALID_SIGNAL_NUMBER, 50233, kind7);
        ASTORE_W = new Opcode("ASTORE_W", WinError.ERROR_THREAD_1_INACTIVE, 50234, kind7);
        IINC_W = new Opcode("IINC_W", 211, 50308, Instruction.Kind.WIDE_LOCAL_SHORT);
        RET_W = new Opcode("RET_W", WinError.ERROR_LOCKED, 50345, kind7);
        Set set = Set.PICOJAVA;
        LOAD_UBYTE = new Opcode("LOAD_UBYTE", 213, set, 65024);
        LOAD_BYTE = new Opcode("LOAD_BYTE", WinError.ERROR_TOO_MANY_MODULES, set, 65025);
        LOAD_CHAR = new Opcode("LOAD_CHAR", WinError.ERROR_NESTING_NOT_ALLOWED, set, 65026);
        LOAD_SHORT = new Opcode("LOAD_SHORT", WinError.ERROR_EXE_MACHINE_TYPE_MISMATCH, set, 65027);
        LOAD_WORD = new Opcode("LOAD_WORD", WinError.ERROR_EXE_CANNOT_MODIFY_SIGNED_BINARY, set, 65028);
        RET_FROM_SUB = new Opcode("RET_FROM_SUB", WinError.ERROR_EXE_CANNOT_MODIFY_STRONG_SIGNED_BINARY, set, 65029);
        LOAD_CHAR_OE = new Opcode("LOAD_CHAR_OE", 219, set, 65034);
        LOAD_SHORT_OE = new Opcode("LOAD_SHORT_OE", WinError.ERROR_FILE_CHECKED_OUT, set, 65035);
        LOAD_WORD_OE = new Opcode("LOAD_WORD_OE", WinError.ERROR_CHECKOUT_REQUIRED, set, 65036);
        NCLOAD_UBYTE = new Opcode("NCLOAD_UBYTE", WinError.ERROR_BAD_FILE_TYPE, set, 65040);
        NCLOAD_BYTE = new Opcode("NCLOAD_BYTE", WinError.ERROR_FILE_TOO_LARGE, set, 65041);
        NCLOAD_CHAR = new Opcode("NCLOAD_CHAR", WinError.ERROR_FORMS_AUTH_REQUIRED, set, 65042);
        NCLOAD_SHORT = new Opcode("NCLOAD_SHORT", WinError.ERROR_VIRUS_INFECTED, set, 65043);
        NCLOAD_WORD = new Opcode("NCLOAD_WORD", WinError.ERROR_VIRUS_DELETED, set, 65044);
        NCLOAD_CHAR_OE = new Opcode("NCLOAD_CHAR_OE", 227, set, 65050);
        NCLOAD_SHORT_OE = new Opcode("NCLOAD_SHORT_OE", 228, set, 65051);
        NCLOAD_WORD_OE = new Opcode("NCLOAD_WORD_OE", WinError.ERROR_PIPE_LOCAL, set, 65052);
        CACHE_FLUSH = new Opcode("CACHE_FLUSH", WinError.ERROR_BAD_PIPE, set, 65054);
        STORE_BYTE = new Opcode("STORE_BYTE", WinError.ERROR_PIPE_BUSY, set, 65056);
        STORE_SHORT = new Opcode("STORE_SHORT", WinError.ERROR_NO_DATA, set, 65058);
        STORE_WORD = new Opcode("STORE_WORD", WinError.ERROR_PIPE_NOT_CONNECTED, set, 65060);
        STORE_SHORT_OE = new Opcode("STORE_SHORT_OE", WinError.ERROR_MORE_DATA, set, 65066);
        STORE_WORD_OE = new Opcode("STORE_WORD_OE", 235, set, 65068);
        NCSTORE_BYTE = new Opcode("NCSTORE_BYTE", 236, set, 65072);
        NCSTORE_SHORT = new Opcode("NCSTORE_SHORT", 237, set, 65074);
        NCSTORE_WORD = new Opcode("NCSTORE_WORD", 238, set, 65076);
        NCSTORE_SHORT_OE = new Opcode("NCSTORE_SHORT_OE", 239, set, 65082);
        NCSTORE_WORD_OE = new Opcode("NCSTORE_WORD_OE", 240, set, 65084);
        ZERO_LINE = new Opcode("ZERO_LINE", 241, set, 65086);
        ENTER_SYNC_METHOD = new Opcode("ENTER_SYNC_METHOD", 242, set, 65087);
        PRIV_LOAD_UBYTE = new Opcode("PRIV_LOAD_UBYTE", 243, set, Winspool.PRINTER_CHANGE_JOB);
        PRIV_LOAD_BYTE = new Opcode("PRIV_LOAD_BYTE", 244, set, 65281);
        PRIV_LOAD_CHAR = new Opcode("PRIV_LOAD_CHAR", 245, set, 65282);
        PRIV_LOAD_SHORT = new Opcode("PRIV_LOAD_SHORT", 246, set, 65283);
        PRIV_LOAD_WORD = new Opcode("PRIV_LOAD_WORD", Const.SAME_LOCALS_1_STACK_ITEM_FRAME_EXTENDED, set, 65284);
        PRIV_RET_FROM_TRAP = new Opcode("PRIV_RET_FROM_TRAP", Const.CHOP_FRAME, set, 65285);
        PRIV_READ_DCACHE_TAG = new Opcode("PRIV_READ_DCACHE_TAG", 249, set, 65286);
        PRIV_READ_DCACHE_DATA = new Opcode("PRIV_READ_DCACHE_DATA", Const.CHOP_FRAME_MAX, set, 65287);
        PRIV_LOAD_CHAR_OE = new Opcode("PRIV_LOAD_CHAR_OE", Const.SAME_FRAME_EXTENDED, set, 65290);
        PRIV_LOAD_SHORT_OE = new Opcode("PRIV_LOAD_SHORT_OE", Const.APPEND_FRAME, set, 65291);
        PRIV_LOAD_WORD_OE = new Opcode("PRIV_LOAD_WORD_OE", 253, set, 65292);
        PRIV_READ_ICACHE_TAG = new Opcode("PRIV_READ_ICACHE_TAG", 254, set, 65294);
        PRIV_READ_ICACHE_DATA = new Opcode("PRIV_READ_ICACHE_DATA", 255, set, 65295);
        PRIV_NCLOAD_UBYTE = new Opcode("PRIV_NCLOAD_UBYTE", 256, set, 65296);
        PRIV_NCLOAD_BYTE = new Opcode("PRIV_NCLOAD_BYTE", 257, set, 65297);
        PRIV_NCLOAD_CHAR = new Opcode("PRIV_NCLOAD_CHAR", 258, set, 65298);
        PRIV_NCLOAD_SHORT = new Opcode("PRIV_NCLOAD_SHORT", 259, set, 65299);
        PRIV_NCLOAD_WORD = new Opcode("PRIV_NCLOAD_WORD", 260, set, 65300);
        PRIV_POWERDOWN = new Opcode("PRIV_POWERDOWN", WinUser.WM_SYSKEYUP, set, 65302);
        PRIV_READ_SCACHE_DATA = new Opcode("PRIV_READ_SCACHE_DATA", 262, set, 65303);
        PRIV_NCLOAD_CHAR_OE = new Opcode("PRIV_NCLOAD_CHAR_OE", 263, set, 65306);
        PRIV_NCLOAD_SHORT_OE = new Opcode("PRIV_NCLOAD_SHORT_OE", 264, set, 65307);
        PRIV_NCLOAD_WORD_OE = new Opcode("PRIV_NCLOAD_WORD_OE", 265, set, 65308);
        PRIV_CACHE_FLUSH = new Opcode("PRIV_CACHE_FLUSH", WinError.ERROR_CANNOT_COPY, set, 65310);
        PRIV_CACHE_INDEX_FLUSH = new Opcode("PRIV_CACHE_INDEX_FLUSH", WinError.ERROR_DIRECTORY, set, 65311);
        PRIV_STORE_BYTE = new Opcode("PRIV_STORE_BYTE", 268, set, 65312);
        PRIV_STORE_SHORT = new Opcode("PRIV_STORE_SHORT", 269, set, 65314);
        PRIV_STORE_WORD = new Opcode("PRIV_STORE_WORD", ByteCodes.ishll, set, 65316);
        PRIV_WRITE_DCACHE_TAG = new Opcode("PRIV_WRITE_DCACHE_TAG", ByteCodes.lshll, set, 65318);
        PRIV_WRITE_DCACHE_DATA = new Opcode("PRIV_WRITE_DCACHE_DATA", ByteCodes.ishrl, set, 65319);
        PRIV_STORE_SHORT_OE = new Opcode("PRIV_STORE_SHORT_OE", ByteCodes.lshrl, set, 65322);
        PRIV_STORE_WORD_OE = new Opcode("PRIV_STORE_WORD_OE", 274, set, 65324);
        PRIV_WRITE_ICACHE_TAG = new Opcode("PRIV_WRITE_ICACHE_TAG", 275, set, 65326);
        PRIV_WRITE_ICACHE_DATA = new Opcode("PRIV_WRITE_ICACHE_DATA", 276, set, 65327);
        PRIV_NCSTORE_BYTE = new Opcode("PRIV_NCSTORE_BYTE", 277, set, 65328);
        PRIV_NCSTORE_SHORT = new Opcode("PRIV_NCSTORE_SHORT", WinError.ERROR_INVALID_EA_HANDLE, set, 65330);
        PRIV_NCSTORE_WORD = new Opcode("PRIV_NCSTORE_WORD", 279, set, 65332);
        PRIV_RESET = new Opcode("PRIV_RESET", 280, set, 65334);
        PRIV_WRITE_SCACHE_DATA = new Opcode("PRIV_WRITE_SCACHE_DATA", 281, set, 65335);
        PRIV_NCSTORE_SHORT_OE = new Opcode("PRIV_NCSTORE_SHORT_OE", WinError.ERROR_EAS_NOT_SUPPORTED, set, 65338);
        PRIV_NCSTORE_WORD_OE = new Opcode("PRIV_NCSTORE_WORD_OE", 283, set, 65340);
        PRIV_ZERO_LINE = new Opcode("PRIV_ZERO_LINE", 284, set, 65342);
        PRIV_READ_REG_0 = new Opcode("PRIV_READ_REG_0", 285, set, 65344);
        PRIV_READ_REG_1 = new Opcode("PRIV_READ_REG_1", 286, set, 65345);
        PRIV_READ_REG_2 = new Opcode("PRIV_READ_REG_2", 287, set, 65346);
        PRIV_READ_REG_3 = new Opcode("PRIV_READ_REG_3", WinError.ERROR_NOT_OWNER, set, 65347);
        PRIV_READ_REG_4 = new Opcode("PRIV_READ_REG_4", 289, set, 65348);
        PRIV_READ_REG_5 = new Opcode("PRIV_READ_REG_5", 290, set, 65349);
        PRIV_READ_REG_6 = new Opcode("PRIV_READ_REG_6", 291, set, 65350);
        PRIV_READ_REG_7 = new Opcode("PRIV_READ_REG_7", 292, set, 65351);
        PRIV_READ_REG_8 = new Opcode("PRIV_READ_REG_8", 293, set, 65352);
        PRIV_READ_REG_9 = new Opcode("PRIV_READ_REG_9", 294, set, 65353);
        PRIV_READ_REG_10 = new Opcode("PRIV_READ_REG_10", 295, set, 65354);
        PRIV_READ_REG_11 = new Opcode("PRIV_READ_REG_11", 296, set, 65355);
        PRIV_READ_REG_12 = new Opcode("PRIV_READ_REG_12", 297, set, 65356);
        PRIV_READ_REG_13 = new Opcode("PRIV_READ_REG_13", WinError.ERROR_TOO_MANY_POSTS, set, 65357);
        PRIV_READ_REG_14 = new Opcode("PRIV_READ_REG_14", WinError.ERROR_PARTIAL_COPY, set, 65358);
        PRIV_READ_REG_15 = new Opcode("PRIV_READ_REG_15", 300, set, 65359);
        PRIV_READ_REG_16 = new Opcode("PRIV_READ_REG_16", WinError.ERROR_INVALID_OPLOCK_PROTOCOL, set, 65360);
        PRIV_READ_REG_17 = new Opcode("PRIV_READ_REG_17", WinError.ERROR_DISK_TOO_FRAGMENTED, set, 65361);
        PRIV_READ_REG_18 = new Opcode("PRIV_READ_REG_18", WinError.ERROR_DELETE_PENDING, set, 65362);
        PRIV_READ_REG_19 = new Opcode("PRIV_READ_REG_19", 304, set, 65363);
        PRIV_READ_REG_20 = new Opcode("PRIV_READ_REG_20", 305, set, 65364);
        PRIV_READ_REG_21 = new Opcode("PRIV_READ_REG_21", 306, set, 65365);
        PRIV_READ_REG_22 = new Opcode("PRIV_READ_REG_22", 307, set, 65366);
        PRIV_READ_REG_23 = new Opcode("PRIV_READ_REG_23", 308, set, 65367);
        PRIV_READ_REG_24 = new Opcode("PRIV_READ_REG_24", 309, set, 65368);
        PRIV_READ_REG_25 = new Opcode("PRIV_READ_REG_25", 310, set, 65369);
        PRIV_READ_REG_26 = new Opcode("PRIV_READ_REG_26", 311, set, 65370);
        PRIV_READ_REG_27 = new Opcode("PRIV_READ_REG_27", 312, set, 65371);
        PRIV_READ_REG_28 = new Opcode("PRIV_READ_REG_28", 313, set, 65372);
        PRIV_READ_REG_29 = new Opcode("PRIV_READ_REG_29", 314, set, 65373);
        PRIV_READ_REG_30 = new Opcode("PRIV_READ_REG_30", 315, set, 65374);
        PRIV_READ_REG_31 = new Opcode("PRIV_READ_REG_31", 316, set, 65375);
        PRIV_WRITE_REG_0 = new Opcode("PRIV_WRITE_REG_0", WinError.ERROR_MR_MID_NOT_FOUND, set, 65376);
        PRIV_WRITE_REG_1 = new Opcode("PRIV_WRITE_REG_1", WinError.ERROR_SCOPE_NOT_FOUND, set, 65377);
        PRIV_WRITE_REG_2 = new Opcode("PRIV_WRITE_REG_2", WinNT.SERVICE_TYPE_ALL, set, 65378);
        PRIV_WRITE_REG_3 = new Opcode("PRIV_WRITE_REG_3", 320, set, 65379);
        PRIV_WRITE_REG_4 = new Opcode("PRIV_WRITE_REG_4", 321, set, 65380);
        PRIV_WRITE_REG_5 = new Opcode("PRIV_WRITE_REG_5", 322, set, 65381);
        PRIV_WRITE_REG_6 = new Opcode("PRIV_WRITE_REG_6", 323, set, 65382);
        PRIV_WRITE_REG_7 = new Opcode("PRIV_WRITE_REG_7", 324, set, 65383);
        PRIV_WRITE_REG_8 = new Opcode("PRIV_WRITE_REG_8", 325, set, 65384);
        PRIV_WRITE_REG_9 = new Opcode("PRIV_WRITE_REG_9", 326, set, 65385);
        PRIV_WRITE_REG_10 = new Opcode("PRIV_WRITE_REG_10", 327, set, 65386);
        PRIV_WRITE_REG_11 = new Opcode("PRIV_WRITE_REG_11", 328, set, 65387);
        PRIV_WRITE_REG_12 = new Opcode("PRIV_WRITE_REG_12", 329, set, 65388);
        PRIV_WRITE_REG_13 = new Opcode("PRIV_WRITE_REG_13", 330, set, 65389);
        PRIV_WRITE_REG_14 = new Opcode("PRIV_WRITE_REG_14", 331, set, 65390);
        PRIV_WRITE_REG_15 = new Opcode("PRIV_WRITE_REG_15", 332, set, 65391);
        PRIV_WRITE_REG_16 = new Opcode("PRIV_WRITE_REG_16", 333, set, 65392);
        PRIV_WRITE_REG_17 = new Opcode("PRIV_WRITE_REG_17", 334, set, 65393);
        PRIV_WRITE_REG_18 = new Opcode("PRIV_WRITE_REG_18", 335, set, 65394);
        PRIV_WRITE_REG_19 = new Opcode("PRIV_WRITE_REG_19", 336, set, 65395);
        PRIV_WRITE_REG_20 = new Opcode("PRIV_WRITE_REG_20", 337, set, 65396);
        PRIV_WRITE_REG_21 = new Opcode("PRIV_WRITE_REG_21", 338, set, 65397);
        PRIV_WRITE_REG_22 = new Opcode("PRIV_WRITE_REG_22", 339, set, 65398);
        PRIV_WRITE_REG_23 = new Opcode("PRIV_WRITE_REG_23", 340, set, 65399);
        PRIV_WRITE_REG_24 = new Opcode("PRIV_WRITE_REG_24", 341, set, 65400);
        PRIV_WRITE_REG_25 = new Opcode("PRIV_WRITE_REG_25", 342, set, 65401);
        PRIV_WRITE_REG_26 = new Opcode("PRIV_WRITE_REG_26", 343, set, 65402);
        PRIV_WRITE_REG_27 = new Opcode("PRIV_WRITE_REG_27", 344, set, 65403);
        PRIV_WRITE_REG_28 = new Opcode("PRIV_WRITE_REG_28", 345, set, 65404);
        PRIV_WRITE_REG_29 = new Opcode("PRIV_WRITE_REG_29", 346, set, 65405);
        PRIV_WRITE_REG_30 = new Opcode("PRIV_WRITE_REG_30", 347, set, 65406);
        PRIV_WRITE_REG_31 = new Opcode("PRIV_WRITE_REG_31", 348, set, 65407);
        $VALUES = $values();
        stdOpcodes = new Opcode[256];
        wideOpcodes = new Opcode[256];
        nonPrivOpcodes = new Opcode[256];
        privOpcodes = new Opcode[256];
        for (Opcode opcode : values()) {
            getOpcodeBlock(opcode.opcode >> 8)[opcode.opcode & 255] = opcode;
        }
    }

    private Opcode(String str, int i, Set set, int i2) {
        this(str, i, set, i2, set == Set.STANDARD ? Instruction.Kind.NO_OPERANDS : Instruction.Kind.WIDE_NO_OPERANDS);
    }

    public static Opcode get(int i, int i2) {
        Opcode[] opcodeBlock = getOpcodeBlock(i);
        if (opcodeBlock == null) {
            return null;
        }
        return opcodeBlock[i2];
    }

    private static Opcode[] getOpcodeBlock(int i) {
        if (i == 0) {
            return stdOpcodes;
        }
        if (i == 196) {
            return wideOpcodes;
        }
        if (i == 254) {
            return nonPrivOpcodes;
        }
        if (i != 255) {
            return null;
        }
        return privOpcodes;
    }

    public static Opcode valueOf(String str) {
        return (Opcode) Enum.valueOf(Opcode.class, str);
    }

    public static Opcode[] values() {
        return (Opcode[]) $VALUES.clone();
    }

    public static Opcode get(int i) {
        return stdOpcodes[i];
    }

    private Opcode(String str, int i, int i2, Instruction.Kind kind) {
        this(str, i, Set.STANDARD, i2, kind);
    }

    private Opcode(String str, int i, int i2) {
        this(str, i, Set.STANDARD, i2, Instruction.Kind.NO_OPERANDS);
    }

    private Opcode(String str, int i, Set set, int i2, Instruction.Kind kind) {
        super(str, i);
        this.set = set;
        this.opcode = i2;
        this.kind = kind;
    }
}
