package androidx.compose.material.icons.twotone;

import androidx.compose.material.icons.Icons;
import androidx.compose.ui.graphics.Brush;
import androidx.compose.ui.graphics.Color;
import androidx.compose.ui.graphics.SolidColor;
import androidx.compose.ui.graphics.StrokeCap;
import androidx.compose.ui.graphics.StrokeJoin;
import androidx.compose.ui.graphics.vector.ImageVector;
import androidx.compose.ui.graphics.vector.PathBuilder;
import androidx.compose.ui.graphics.vector.VectorKt;
import androidx.compose.ui.unit.Dp;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.DefaultConstructorMarker;

/* JADX INFO: loaded from: /workspace/dex_all/classes.dex */
@Metadata(d1 = {"\u0000\u0010\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\"\u0010\u0010\u0000\u001a\u0004\u0018\u00010\u0001X\u0082\u000e¢\u0006\u0002\n\u0000\"\u0015\u0010\u0002\u001a\u00020\u0001*\u00020\u00038F¢\u0006\u0006\u001a\u0004\b\u0004\u0010\u0005¨\u0006\u0006"}, d2 = {"_blurOn", "Landroidx/compose/ui/graphics/vector/ImageVector;", "BlurOn", "Landroidx/compose/material/icons/Icons$TwoTone;", "getBlurOn", "(Landroidx/compose/material/icons/Icons$TwoTone;)Landroidx/compose/ui/graphics/vector/ImageVector;", "material-icons-extended_release"}, k = 2, mv = {1, 8, 0}, xi = 48)
public final class BlurOnKt {
    private static ImageVector _blurOn;

    public static final ImageVector getBlurOn(Icons.TwoTone twoTone) {
        ImageVector imageVector = _blurOn;
        if (imageVector != null) {
            imageVector.getClass();
            return imageVector;
        }
        ImageVector.Builder builder = new ImageVector.Builder("TwoTone.BlurOn", Dp.constructor-impl(24.0f), Dp.constructor-impl(24.0f), 24.0f, 24.0f, 0L, 0, false, 96, (DefaultConstructorMarker) null);
        int defaultFillType = VectorKt.getDefaultFillType();
        Color.Companion companion = Color.Companion;
        SolidColor solidColor = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        StrokeCap.Companion companion2 = StrokeCap.Companion;
        int i = companion2.getButt-KaPHkGw();
        StrokeJoin.Companion companion3 = StrokeJoin.Companion;
        int i2 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder = new PathBuilder();
        pathBuilder.moveTo(14.0f, 10.0f);
        pathBuilder.moveToRelative(-1.5f, 0.0f);
        pathBuilder.arcToRelative(1.5f, 1.5f, 0.0f, true, true, 3.0f, 0.0f);
        pathBuilder.arcToRelative(1.5f, 1.5f, 0.0f, true, true, -3.0f, 0.0f);
        Unit unit = Unit.INSTANCE;
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder.getNodes(), defaultFillType, "", solidColor, 1.0f, (Brush) null, 1.0f, 1.0f, i, i2, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType2 = VectorKt.getDefaultFillType();
        SolidColor solidColor2 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i3 = companion2.getButt-KaPHkGw();
        int i4 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder2 = new PathBuilder();
        pathBuilder2.moveTo(14.0f, 18.0f);
        pathBuilder2.moveToRelative(-1.0f, 0.0f);
        pathBuilder2.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder2.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder2.getNodes(), defaultFillType2, "", solidColor2, 1.0f, (Brush) null, 1.0f, 1.0f, i3, i4, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType3 = VectorKt.getDefaultFillType();
        SolidColor solidColor3 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i5 = companion2.getButt-KaPHkGw();
        int i6 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder3 = new PathBuilder();
        pathBuilder3.moveTo(14.0f, 14.0f);
        pathBuilder3.moveToRelative(-1.5f, 0.0f);
        pathBuilder3.arcToRelative(1.5f, 1.5f, 0.0f, true, true, 3.0f, 0.0f);
        pathBuilder3.arcToRelative(1.5f, 1.5f, 0.0f, true, true, -3.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder3.getNodes(), defaultFillType3, "", solidColor3, 1.0f, (Brush) null, 1.0f, 1.0f, i5, i6, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType4 = VectorKt.getDefaultFillType();
        SolidColor solidColor4 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i7 = companion2.getButt-KaPHkGw();
        int i8 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder4 = new PathBuilder();
        pathBuilder4.moveTo(14.0f, 6.0f);
        pathBuilder4.moveToRelative(-1.0f, 0.0f);
        pathBuilder4.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder4.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder4.getNodes(), defaultFillType4, "", solidColor4, 1.0f, (Brush) null, 1.0f, 1.0f, i7, i8, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType5 = VectorKt.getDefaultFillType();
        SolidColor solidColor5 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i9 = companion2.getButt-KaPHkGw();
        int i10 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder5 = new PathBuilder();
        pathBuilder5.moveTo(3.0f, 9.5f);
        pathBuilder5.curveToRelative(-0.28f, 0.0f, -0.5f, 0.22f, -0.5f, 0.5f);
        pathBuilder5.reflectiveCurveToRelative(0.22f, 0.5f, 0.5f, 0.5f);
        pathBuilder5.reflectiveCurveToRelative(0.5f, -0.22f, 0.5f, -0.5f);
        pathBuilder5.reflectiveCurveToRelative(-0.22f, -0.5f, -0.5f, -0.5f);
        pathBuilder5.close();
        pathBuilder5.moveTo(14.5f, 3.0f);
        pathBuilder5.curveToRelative(0.0f, -0.28f, -0.22f, -0.5f, -0.5f, -0.5f);
        pathBuilder5.reflectiveCurveToRelative(-0.5f, 0.22f, -0.5f, 0.5f);
        pathBuilder5.reflectiveCurveToRelative(0.22f, 0.5f, 0.5f, 0.5f);
        pathBuilder5.reflectiveCurveToRelative(0.5f, -0.22f, 0.5f, -0.5f);
        pathBuilder5.close();
        pathBuilder5.moveTo(21.0f, 14.5f);
        pathBuilder5.curveToRelative(0.28f, 0.0f, 0.5f, -0.22f, 0.5f, -0.5f);
        pathBuilder5.reflectiveCurveToRelative(-0.22f, -0.5f, -0.5f, -0.5f);
        pathBuilder5.reflectiveCurveToRelative(-0.5f, 0.22f, -0.5f, 0.5f);
        pathBuilder5.reflectiveCurveToRelative(0.22f, 0.5f, 0.5f, 0.5f);
        pathBuilder5.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder5.getNodes(), defaultFillType5, "", solidColor5, 1.0f, (Brush) null, 1.0f, 1.0f, i9, i10, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType6 = VectorKt.getDefaultFillType();
        SolidColor solidColor6 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i11 = companion2.getButt-KaPHkGw();
        int i12 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder6 = new PathBuilder();
        pathBuilder6.moveTo(18.0f, 18.0f);
        pathBuilder6.moveToRelative(-1.0f, 0.0f);
        pathBuilder6.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder6.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder6.getNodes(), defaultFillType6, "", solidColor6, 1.0f, (Brush) null, 1.0f, 1.0f, i11, i12, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType7 = VectorKt.getDefaultFillType();
        SolidColor solidColor7 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i13 = companion2.getButt-KaPHkGw();
        int i14 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder7 = new PathBuilder();
        pathBuilder7.moveTo(13.5f, 21.0f);
        pathBuilder7.curveToRelative(0.0f, 0.28f, 0.22f, 0.5f, 0.5f, 0.5f);
        pathBuilder7.reflectiveCurveToRelative(0.5f, -0.22f, 0.5f, -0.5f);
        pathBuilder7.reflectiveCurveToRelative(-0.22f, -0.5f, -0.5f, -0.5f);
        pathBuilder7.reflectiveCurveToRelative(-0.5f, 0.22f, -0.5f, 0.5f);
        pathBuilder7.close();
        pathBuilder7.moveTo(21.0f, 10.5f);
        pathBuilder7.curveToRelative(0.28f, 0.0f, 0.5f, -0.22f, 0.5f, -0.5f);
        pathBuilder7.reflectiveCurveToRelative(-0.22f, -0.5f, -0.5f, -0.5f);
        pathBuilder7.reflectiveCurveToRelative(-0.5f, 0.22f, -0.5f, 0.5f);
        pathBuilder7.reflectiveCurveToRelative(0.22f, 0.5f, 0.5f, 0.5f);
        pathBuilder7.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder7.getNodes(), defaultFillType7, "", solidColor7, 1.0f, (Brush) null, 1.0f, 1.0f, i13, i14, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType8 = VectorKt.getDefaultFillType();
        SolidColor solidColor8 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i15 = companion2.getButt-KaPHkGw();
        int i16 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder8 = new PathBuilder();
        pathBuilder8.moveTo(18.0f, 14.0f);
        pathBuilder8.moveToRelative(-1.0f, 0.0f);
        pathBuilder8.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder8.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder8.getNodes(), defaultFillType8, "", solidColor8, 1.0f, (Brush) null, 1.0f, 1.0f, i15, i16, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType9 = VectorKt.getDefaultFillType();
        SolidColor solidColor9 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i17 = companion2.getButt-KaPHkGw();
        int i18 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder9 = new PathBuilder();
        pathBuilder9.moveTo(18.0f, 6.0f);
        pathBuilder9.moveToRelative(-1.0f, 0.0f);
        pathBuilder9.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder9.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder9.getNodes(), defaultFillType9, "", solidColor9, 1.0f, (Brush) null, 1.0f, 1.0f, i17, i18, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType10 = VectorKt.getDefaultFillType();
        SolidColor solidColor10 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i19 = companion2.getButt-KaPHkGw();
        int i20 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder10 = new PathBuilder();
        pathBuilder10.moveTo(6.0f, 18.0f);
        pathBuilder10.moveToRelative(-1.0f, 0.0f);
        pathBuilder10.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder10.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder10.getNodes(), defaultFillType10, "", solidColor10, 1.0f, (Brush) null, 1.0f, 1.0f, i19, i20, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType11 = VectorKt.getDefaultFillType();
        SolidColor solidColor11 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i21 = companion2.getButt-KaPHkGw();
        int i22 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder11 = new PathBuilder();
        pathBuilder11.moveTo(6.0f, 14.0f);
        pathBuilder11.moveToRelative(-1.0f, 0.0f);
        pathBuilder11.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder11.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder11.getNodes(), defaultFillType11, "", solidColor11, 1.0f, (Brush) null, 1.0f, 1.0f, i21, i22, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType12 = VectorKt.getDefaultFillType();
        SolidColor solidColor12 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i23 = companion2.getButt-KaPHkGw();
        int i24 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder12 = new PathBuilder();
        pathBuilder12.moveTo(3.5f, 14.0f);
        pathBuilder12.curveToRelative(0.0f, -0.28f, -0.22f, -0.5f, -0.5f, -0.5f);
        pathBuilder12.reflectiveCurveToRelative(-0.5f, 0.22f, -0.5f, 0.5f);
        pathBuilder12.reflectiveCurveToRelative(0.22f, 0.5f, 0.5f, 0.5f);
        pathBuilder12.reflectiveCurveToRelative(0.5f, -0.22f, 0.5f, -0.5f);
        pathBuilder12.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder12.getNodes(), defaultFillType12, "", solidColor12, 1.0f, (Brush) null, 1.0f, 1.0f, i23, i24, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType13 = VectorKt.getDefaultFillType();
        SolidColor solidColor13 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i25 = companion2.getButt-KaPHkGw();
        int i26 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder13 = new PathBuilder();
        pathBuilder13.moveTo(10.0f, 6.0f);
        pathBuilder13.moveToRelative(-1.0f, 0.0f);
        pathBuilder13.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder13.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder13.getNodes(), defaultFillType13, "", solidColor13, 1.0f, (Brush) null, 1.0f, 1.0f, i25, i26, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType14 = VectorKt.getDefaultFillType();
        SolidColor solidColor14 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i27 = companion2.getButt-KaPHkGw();
        int i28 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder14 = new PathBuilder();
        pathBuilder14.moveTo(6.0f, 10.0f);
        pathBuilder14.moveToRelative(-1.0f, 0.0f);
        pathBuilder14.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder14.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder14.getNodes(), defaultFillType14, "", solidColor14, 1.0f, (Brush) null, 1.0f, 1.0f, i27, i28, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType15 = VectorKt.getDefaultFillType();
        SolidColor solidColor15 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i29 = companion2.getButt-KaPHkGw();
        int i30 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder15 = new PathBuilder();
        pathBuilder15.moveTo(6.0f, 6.0f);
        pathBuilder15.moveToRelative(-1.0f, 0.0f);
        pathBuilder15.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder15.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder15.getNodes(), defaultFillType15, "", solidColor15, 1.0f, (Brush) null, 1.0f, 1.0f, i29, i30, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType16 = VectorKt.getDefaultFillType();
        SolidColor solidColor16 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i31 = companion2.getButt-KaPHkGw();
        int i32 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder16 = new PathBuilder();
        pathBuilder16.moveTo(9.5f, 21.0f);
        pathBuilder16.curveToRelative(0.0f, 0.28f, 0.22f, 0.5f, 0.5f, 0.5f);
        pathBuilder16.reflectiveCurveToRelative(0.5f, -0.22f, 0.5f, -0.5f);
        pathBuilder16.reflectiveCurveToRelative(-0.22f, -0.5f, -0.5f, -0.5f);
        pathBuilder16.reflectiveCurveToRelative(-0.5f, 0.22f, -0.5f, 0.5f);
        pathBuilder16.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder16.getNodes(), defaultFillType16, "", solidColor16, 1.0f, (Brush) null, 1.0f, 1.0f, i31, i32, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType17 = VectorKt.getDefaultFillType();
        SolidColor solidColor17 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i33 = companion2.getButt-KaPHkGw();
        int i34 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder17 = new PathBuilder();
        pathBuilder17.moveTo(10.0f, 18.0f);
        pathBuilder17.moveToRelative(-1.0f, 0.0f);
        pathBuilder17.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder17.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder17.getNodes(), defaultFillType17, "", solidColor17, 1.0f, (Brush) null, 1.0f, 1.0f, i33, i34, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType18 = VectorKt.getDefaultFillType();
        SolidColor solidColor18 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i35 = companion2.getButt-KaPHkGw();
        int i36 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder18 = new PathBuilder();
        pathBuilder18.moveTo(10.5f, 3.0f);
        pathBuilder18.curveToRelative(0.0f, -0.28f, -0.22f, -0.5f, -0.5f, -0.5f);
        pathBuilder18.reflectiveCurveToRelative(-0.5f, 0.22f, -0.5f, 0.5f);
        pathBuilder18.reflectiveCurveToRelative(0.22f, 0.5f, 0.5f, 0.5f);
        pathBuilder18.reflectiveCurveToRelative(0.5f, -0.22f, 0.5f, -0.5f);
        pathBuilder18.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder18.getNodes(), defaultFillType18, "", solidColor18, 1.0f, (Brush) null, 1.0f, 1.0f, i35, i36, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType19 = VectorKt.getDefaultFillType();
        SolidColor solidColor19 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i37 = companion2.getButt-KaPHkGw();
        int i38 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder19 = new PathBuilder();
        pathBuilder19.moveTo(10.0f, 14.0f);
        pathBuilder19.moveToRelative(-1.5f, 0.0f);
        pathBuilder19.arcToRelative(1.5f, 1.5f, 0.0f, true, true, 3.0f, 0.0f);
        pathBuilder19.arcToRelative(1.5f, 1.5f, 0.0f, true, true, -3.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder19.getNodes(), defaultFillType19, "", solidColor19, 1.0f, (Brush) null, 1.0f, 1.0f, i37, i38, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType20 = VectorKt.getDefaultFillType();
        SolidColor solidColor20 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i39 = companion2.getButt-KaPHkGw();
        int i40 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder20 = new PathBuilder();
        pathBuilder20.moveTo(10.0f, 10.0f);
        pathBuilder20.moveToRelative(-1.5f, 0.0f);
        pathBuilder20.arcToRelative(1.5f, 1.5f, 0.0f, true, true, 3.0f, 0.0f);
        pathBuilder20.arcToRelative(1.5f, 1.5f, 0.0f, true, true, -3.0f, 0.0f);
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder20.getNodes(), defaultFillType20, "", solidColor20, 1.0f, (Brush) null, 1.0f, 1.0f, i39, i40, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType21 = VectorKt.getDefaultFillType();
        SolidColor solidColor21 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i41 = companion2.getButt-KaPHkGw();
        int i42 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder21 = new PathBuilder();
        pathBuilder21.moveTo(18.0f, 10.0f);
        pathBuilder21.moveToRelative(-1.0f, 0.0f);
        pathBuilder21.arcToRelative(1.0f, 1.0f, 0.0f, true, true, 2.0f, 0.0f);
        pathBuilder21.arcToRelative(1.0f, 1.0f, 0.0f, true, true, -2.0f, 0.0f);
        ImageVector imageVectorBuild = ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder21.getNodes(), defaultFillType21, "", solidColor21, 1.0f, (Brush) null, 1.0f, 1.0f, i41, i42, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null).build();
        _blurOn = imageVectorBuild;
        imageVectorBuild.getClass();
        return imageVectorBuild;
    }
}
