package androidx.compose.material.icons.twotone;

import androidx.compose.material.icons.Icons;
import androidx.compose.ui.graphics.Brush;
import androidx.compose.ui.graphics.Color;
import androidx.compose.ui.graphics.SolidColor;
import androidx.compose.ui.graphics.StrokeCap;
import androidx.compose.ui.graphics.StrokeJoin;
import androidx.compose.ui.graphics.vector.ImageVector;
import androidx.compose.ui.graphics.vector.PathBuilder;
import androidx.compose.ui.graphics.vector.VectorKt;
import androidx.compose.ui.unit.Dp;
import kotlin.Metadata;
import kotlin.jvm.internal.DefaultConstructorMarker;

/* JADX INFO: loaded from: /workspace/dex_all/classes.dex */
@Metadata(d1 = {"\u0000\u0010\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\"\u0010\u0010\u0000\u001a\u0004\u0018\u00010\u0001X\u0082\u000e¢\u0006\u0002\n\u0000\"\u0015\u0010\u0002\u001a\u00020\u0001*\u00020\u00038F¢\u0006\u0006\u001a\u0004\b\u0004\u0010\u0005¨\u0006\u0006"}, d2 = {"_gridOff", "Landroidx/compose/ui/graphics/vector/ImageVector;", "GridOff", "Landroidx/compose/material/icons/Icons$TwoTone;", "getGridOff", "(Landroidx/compose/material/icons/Icons$TwoTone;)Landroidx/compose/ui/graphics/vector/ImageVector;", "material-icons-extended_release"}, k = 2, mv = {1, 8, 0}, xi = 48)
public final class GridOffKt {
    private static ImageVector _gridOff;

    public static final ImageVector getGridOff(Icons.TwoTone twoTone) {
        ImageVector imageVector = _gridOff;
        if (imageVector != null) {
            imageVector.getClass();
            return imageVector;
        }
        ImageVector.Builder builder = new ImageVector.Builder("TwoTone.GridOff", Dp.constructor-impl(24.0f), Dp.constructor-impl(24.0f), 24.0f, 24.0f, 0L, 0, false, 96, (DefaultConstructorMarker) null);
        int defaultFillType = VectorKt.getDefaultFillType();
        Color.Companion companion = Color.Companion;
        SolidColor solidColor = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        StrokeCap.Companion companion2 = StrokeCap.Companion;
        int i = companion2.getButt-KaPHkGw();
        StrokeJoin.Companion companion3 = StrokeJoin.Companion;
        int i2 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder = new PathBuilder();
        pathBuilder.moveTo(20.0f, 14.0f);
        pathBuilder.verticalLineToRelative(-4.0f);
        pathBuilder.horizontalLineToRelative(-4.0f);
        pathBuilder.verticalLineToRelative(2.89f);
        pathBuilder.lineTo(17.11f, 14.0f);
        pathBuilder.close();
        pathBuilder.moveTo(10.0f, 12.55f);
        pathBuilder.lineTo(10.0f, 14.0f);
        pathBuilder.horizontalLineToRelative(1.45f);
        pathBuilder.close();
        pathBuilder.moveTo(14.0f, 10.0f);
        pathBuilder.horizontalLineToRelative(-0.89f);
        pathBuilder.lineToRelative(0.89f, 0.89f);
        pathBuilder.close();
        pathBuilder.moveTo(19.11f, 16.0f);
        pathBuilder.lineToRelative(0.89f, 0.89f);
        pathBuilder.lineTo(20.0f, 16.0f);
        pathBuilder.close();
        pathBuilder.moveTo(8.0f, 4.0f);
        pathBuilder.horizontalLineToRelative(-0.89f);
        pathBuilder.lineToRelative(0.89f, 0.89f);
        pathBuilder.close();
        pathBuilder.moveTo(14.0f, 8.0f);
        pathBuilder.lineTo(14.0f, 4.0f);
        pathBuilder.horizontalLineToRelative(-4.0f);
        pathBuilder.verticalLineToRelative(2.89f);
        pathBuilder.lineTo(11.11f, 8.0f);
        pathBuilder.close();
        pathBuilder.moveTo(16.0f, 4.0f);
        pathBuilder.horizontalLineToRelative(4.0f);
        pathBuilder.verticalLineToRelative(4.0f);
        pathBuilder.horizontalLineToRelative(-4.0f);
        pathBuilder.close();
        pathBuilder.moveTo(10.0f, 16.0f);
        pathBuilder.verticalLineToRelative(4.0f);
        pathBuilder.horizontalLineToRelative(4.0f);
        pathBuilder.verticalLineToRelative(-3.45f);
        pathBuilder.lineToRelative(-0.55f, -0.55f);
        pathBuilder.close();
        pathBuilder.moveTo(4.0f, 10.0f);
        pathBuilder.verticalLineToRelative(4.0f);
        pathBuilder.horizontalLineToRelative(4.0f);
        pathBuilder.verticalLineToRelative(-3.45f);
        pathBuilder.lineTo(7.45f, 10.0f);
        pathBuilder.close();
        pathBuilder.moveTo(16.0f, 20.0f);
        pathBuilder.horizontalLineToRelative(1.45f);
        pathBuilder.lineTo(16.0f, 18.55f);
        pathBuilder.close();
        pathBuilder.moveTo(4.0f, 16.0f);
        pathBuilder.horizontalLineToRelative(4.0f);
        pathBuilder.verticalLineToRelative(4.0f);
        pathBuilder.lineTo(4.0f, 20.0f);
        pathBuilder.close();
        pathBuilder.moveTo(4.0f, 6.55f);
        pathBuilder.lineTo(4.0f, 8.0f);
        pathBuilder.horizontalLineToRelative(1.45f);
        pathBuilder.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder.getNodes(), defaultFillType, "", solidColor, 0.3f, (Brush) null, 0.3f, 1.0f, i, i2, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType2 = VectorKt.getDefaultFillType();
        SolidColor solidColor2 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i3 = companion2.getButt-KaPHkGw();
        int i4 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder2 = new PathBuilder();
        pathBuilder2.moveTo(8.0f, 4.0f);
        pathBuilder2.verticalLineToRelative(0.89f);
        pathBuilder2.lineToRelative(2.0f, 2.0f);
        pathBuilder2.lineTo(10.0f, 4.0f);
        pathBuilder2.horizontalLineToRelative(4.0f);
        pathBuilder2.verticalLineToRelative(4.0f);
        pathBuilder2.horizontalLineToRelative(-2.89f);
        pathBuilder2.lineToRelative(2.0f, 2.0f);
        pathBuilder2.lineTo(14.0f, 10.0f);
        pathBuilder2.verticalLineToRelative(0.89f);
        pathBuilder2.lineToRelative(2.0f, 2.0f);
        pathBuilder2.lineTo(16.0f, 10.0f);
        pathBuilder2.horizontalLineToRelative(4.0f);
        pathBuilder2.verticalLineToRelative(4.0f);
        pathBuilder2.horizontalLineToRelative(-2.89f);
        pathBuilder2.lineToRelative(2.0f, 2.0f);
        pathBuilder2.lineTo(20.0f, 16.0f);
        pathBuilder2.verticalLineToRelative(0.89f);
        pathBuilder2.lineToRelative(2.0f, 2.0f);
        pathBuilder2.lineTo(22.0f, 4.0f);
        pathBuilder2.curveToRelative(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f);
        pathBuilder2.lineTo(5.11f, 2.0f);
        pathBuilder2.lineToRelative(2.0f, 2.0f);
        pathBuilder2.lineTo(8.0f, 4.0f);
        pathBuilder2.close();
        pathBuilder2.moveTo(16.0f, 4.0f);
        pathBuilder2.horizontalLineToRelative(4.0f);
        pathBuilder2.verticalLineToRelative(4.0f);
        pathBuilder2.horizontalLineToRelative(-4.0f);
        pathBuilder2.lineTo(16.0f, 4.0f);
        pathBuilder2.close();
        pathBuilder2.moveTo(1.41f, 1.14f);
        pathBuilder2.lineTo(0.0f, 2.55f);
        pathBuilder2.lineToRelative(2.0f, 2.0f);
        pathBuilder2.lineTo(2.0f, 20.0f);
        pathBuilder2.curveToRelative(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f);
        pathBuilder2.horizontalLineToRelative(15.45f);
        pathBuilder2.lineToRelative(2.01f, 2.01f);
        pathBuilder2.lineToRelative(1.41f, -1.41f);
        pathBuilder2.lineTo(1.41f, 1.14f);
        pathBuilder2.close();
        pathBuilder2.moveTo(10.0f, 12.55f);
        pathBuilder2.lineTo(11.45f, 14.0f);
        pathBuilder2.lineTo(10.0f, 14.0f);
        pathBuilder2.verticalLineToRelative(-1.45f);
        pathBuilder2.close();
        pathBuilder2.moveTo(4.0f, 6.55f);
        pathBuilder2.lineTo(5.45f, 8.0f);
        pathBuilder2.lineTo(4.0f, 8.0f);
        pathBuilder2.lineTo(4.0f, 6.55f);
        pathBuilder2.close();
        pathBuilder2.moveTo(8.0f, 20.0f);
        pathBuilder2.lineTo(4.0f, 20.0f);
        pathBuilder2.verticalLineToRelative(-4.0f);
        pathBuilder2.horizontalLineToRelative(4.0f);
        pathBuilder2.verticalLineToRelative(4.0f);
        pathBuilder2.close();
        pathBuilder2.moveTo(8.0f, 14.0f);
        pathBuilder2.lineTo(4.0f, 14.0f);
        pathBuilder2.verticalLineToRelative(-4.0f);
        pathBuilder2.horizontalLineToRelative(3.45f);
        pathBuilder2.lineToRelative(0.55f, 0.55f);
        pathBuilder2.lineTo(8.0f, 14.0f);
        pathBuilder2.close();
        pathBuilder2.moveTo(14.0f, 20.0f);
        pathBuilder2.horizontalLineToRelative(-4.0f);
        pathBuilder2.verticalLineToRelative(-4.0f);
        pathBuilder2.horizontalLineToRelative(3.45f);
        pathBuilder2.lineToRelative(0.55f, 0.55f);
        pathBuilder2.lineTo(14.0f, 20.0f);
        pathBuilder2.close();
        pathBuilder2.moveTo(16.0f, 20.0f);
        pathBuilder2.verticalLineToRelative(-1.45f);
        pathBuilder2.lineTo(17.45f, 20.0f);
        pathBuilder2.lineTo(16.0f, 20.0f);
        pathBuilder2.close();
        ImageVector imageVectorBuild = ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder2.getNodes(), defaultFillType2, "", solidColor2, 1.0f, (Brush) null, 1.0f, 1.0f, i3, i4, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null).build();
        _gridOff = imageVectorBuild;
        imageVectorBuild.getClass();
        return imageVectorBuild;
    }
}
