package androidx.compose.material.icons.twotone;

import androidx.compose.material.icons.Icons;
import androidx.compose.ui.graphics.Brush;
import androidx.compose.ui.graphics.Color;
import androidx.compose.ui.graphics.SolidColor;
import androidx.compose.ui.graphics.StrokeCap;
import androidx.compose.ui.graphics.StrokeJoin;
import androidx.compose.ui.graphics.vector.ImageVector;
import androidx.compose.ui.graphics.vector.PathBuilder;
import androidx.compose.ui.graphics.vector.VectorKt;
import androidx.compose.ui.unit.Dp;
import kotlin.Metadata;
import kotlin.jvm.internal.DefaultConstructorMarker;

/* JADX INFO: loaded from: /workspace/dex_all/classes.dex */
@Metadata(d1 = {"\u0000\u0010\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\"\u0010\u0010\u0000\u001a\u0004\u0018\u00010\u0001X\u0082\u000e¢\u0006\u0002\n\u0000\"\u0015\u0010\u0002\u001a\u00020\u0001*\u00020\u00038F¢\u0006\u0006\u001a\u0004\b\u0004\u0010\u0005¨\u0006\u0006"}, d2 = {"_hive", "Landroidx/compose/ui/graphics/vector/ImageVector;", "Hive", "Landroidx/compose/material/icons/Icons$TwoTone;", "getHive", "(Landroidx/compose/material/icons/Icons$TwoTone;)Landroidx/compose/ui/graphics/vector/ImageVector;", "material-icons-extended_release"}, k = 2, mv = {1, 8, 0}, xi = 48)
public final class HiveKt {
    private static ImageVector _hive;

    public static final ImageVector getHive(Icons.TwoTone twoTone) {
        ImageVector imageVector = _hive;
        if (imageVector != null) {
            imageVector.getClass();
            return imageVector;
        }
        ImageVector.Builder builder = new ImageVector.Builder("TwoTone.Hive", Dp.constructor-impl(24.0f), Dp.constructor-impl(24.0f), 24.0f, 24.0f, 0L, 0, false, 96, (DefaultConstructorMarker) null);
        int defaultFillType = VectorKt.getDefaultFillType();
        Color.Companion companion = Color.Companion;
        SolidColor solidColor = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        StrokeCap.Companion companion2 = StrokeCap.Companion;
        int i = companion2.getButt-KaPHkGw();
        StrokeJoin.Companion companion3 = StrokeJoin.Companion;
        int i2 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder = new PathBuilder();
        pathBuilder.moveTo(5.92f, 7.0f);
        pathBuilder.lineToRelative(-1.13f, 2.0f);
        pathBuilder.lineToRelative(1.13f, 2.0f);
        pathBuilder.lineToRelative(2.14f, 0.0f);
        pathBuilder.lineToRelative(1.13f, -2.0f);
        pathBuilder.lineToRelative(-1.13f, -2.0f);
        pathBuilder.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder.getNodes(), defaultFillType, "", solidColor, 0.3f, (Brush) null, 0.3f, 1.0f, i, i2, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType2 = VectorKt.getDefaultFillType();
        SolidColor solidColor2 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i3 = companion2.getButt-KaPHkGw();
        int i4 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder2 = new PathBuilder();
        pathBuilder2.moveTo(10.94f, 16.0f);
        pathBuilder2.lineToRelative(-1.14f, 2.02f);
        pathBuilder2.lineToRelative(1.12f, 1.98f);
        pathBuilder2.lineToRelative(2.16f, 0.0f);
        pathBuilder2.lineToRelative(1.12f, -1.98f);
        pathBuilder2.lineToRelative(-1.14f, -2.02f);
        pathBuilder2.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder2.getNodes(), defaultFillType2, "", solidColor2, 0.3f, (Brush) null, 0.3f, 1.0f, i3, i4, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType3 = VectorKt.getDefaultFillType();
        SolidColor solidColor3 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i5 = companion2.getButt-KaPHkGw();
        int i6 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder3 = new PathBuilder();
        pathBuilder3.moveTo(13.06f, 14.0f);
        pathBuilder3.lineToRelative(1.13f, -2.0f);
        pathBuilder3.lineToRelative(-1.13f, -2.0f);
        pathBuilder3.lineToRelative(-2.12f, 0.0f);
        pathBuilder3.lineToRelative(-1.13f, 2.0f);
        pathBuilder3.lineToRelative(1.13f, 2.0f);
        pathBuilder3.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder3.getNodes(), defaultFillType3, "", solidColor3, 0.3f, (Brush) null, 0.3f, 1.0f, i5, i6, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType4 = VectorKt.getDefaultFillType();
        SolidColor solidColor4 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i7 = companion2.getButt-KaPHkGw();
        int i8 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder4 = new PathBuilder();
        pathBuilder4.moveTo(5.92f, 13.0f);
        pathBuilder4.lineToRelative(-1.13f, 2.0f);
        pathBuilder4.lineToRelative(1.13f, 2.0f);
        pathBuilder4.lineToRelative(2.14f, 0.0f);
        pathBuilder4.lineToRelative(1.13f, -2.0f);
        pathBuilder4.lineToRelative(-1.13f, -2.0f);
        pathBuilder4.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder4.getNodes(), defaultFillType4, "", solidColor4, 0.3f, (Brush) null, 0.3f, 1.0f, i7, i8, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType5 = VectorKt.getDefaultFillType();
        SolidColor solidColor5 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i9 = companion2.getButt-KaPHkGw();
        int i10 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder5 = new PathBuilder();
        pathBuilder5.moveTo(15.94f, 7.0f);
        pathBuilder5.lineToRelative(-1.13f, 2.0f);
        pathBuilder5.lineToRelative(1.13f, 2.0f);
        pathBuilder5.lineToRelative(2.14f, 0.0f);
        pathBuilder5.lineToRelative(1.13f, -2.0f);
        pathBuilder5.lineToRelative(-1.13f, -2.0f);
        pathBuilder5.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder5.getNodes(), defaultFillType5, "", solidColor5, 0.3f, (Brush) null, 0.3f, 1.0f, i9, i10, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType6 = VectorKt.getDefaultFillType();
        SolidColor solidColor6 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i11 = companion2.getButt-KaPHkGw();
        int i12 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder6 = new PathBuilder();
        pathBuilder6.moveTo(10.92f, 4.0f);
        pathBuilder6.lineToRelative(-1.12f, 1.98f);
        pathBuilder6.lineToRelative(1.14f, 2.02f);
        pathBuilder6.lineToRelative(2.12f, 0.0f);
        pathBuilder6.lineToRelative(1.14f, -2.02f);
        pathBuilder6.lineToRelative(-1.12f, -1.98f);
        pathBuilder6.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder6.getNodes(), defaultFillType6, "", solidColor6, 0.3f, (Brush) null, 0.3f, 1.0f, i11, i12, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType7 = VectorKt.getDefaultFillType();
        SolidColor solidColor7 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i13 = companion2.getButt-KaPHkGw();
        int i14 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder7 = new PathBuilder();
        pathBuilder7.moveTo(15.94f, 13.0f);
        pathBuilder7.lineToRelative(-1.13f, 2.0f);
        pathBuilder7.lineToRelative(1.13f, 2.0f);
        pathBuilder7.lineToRelative(2.14f, 0.0f);
        pathBuilder7.lineToRelative(1.13f, -2.0f);
        pathBuilder7.lineToRelative(-1.13f, -2.0f);
        pathBuilder7.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder7.getNodes(), defaultFillType7, "", solidColor7, 0.3f, (Brush) null, 0.3f, 1.0f, i13, i14, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType8 = VectorKt.getDefaultFillType();
        SolidColor solidColor8 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i15 = companion2.getButt-KaPHkGw();
        int i16 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder8 = new PathBuilder();
        pathBuilder8.moveTo(21.5f, 9.0f);
        pathBuilder8.lineToRelative(-2.25f, -4.0f);
        pathBuilder8.horizontalLineToRelative(-3.31f);
        pathBuilder8.lineToRelative(-1.69f, -3.0f);
        pathBuilder8.horizontalLineToRelative(-4.5f);
        pathBuilder8.lineTo(8.06f, 5.0f);
        pathBuilder8.horizontalLineTo(4.75f);
        pathBuilder8.lineTo(2.5f, 9.0f);
        pathBuilder8.lineToRelative(1.69f, 3.0f);
        pathBuilder8.lineTo(2.5f, 15.0f);
        pathBuilder8.lineToRelative(2.25f, 4.0f);
        pathBuilder8.horizontalLineToRelative(3.31f);
        pathBuilder8.lineToRelative(1.69f, 3.0f);
        pathBuilder8.horizontalLineToRelative(4.5f);
        pathBuilder8.lineToRelative(1.69f, -3.0f);
        pathBuilder8.horizontalLineToRelative(3.31f);
        pathBuilder8.lineToRelative(2.25f, -4.0f);
        pathBuilder8.lineToRelative(-1.69f, -3.0f);
        pathBuilder8.lineTo(21.5f, 9.0f);
        pathBuilder8.close();
        pathBuilder8.moveTo(8.06f, 17.0f);
        pathBuilder8.horizontalLineTo(5.92f);
        pathBuilder8.lineToRelative(-1.12f, -2.0f);
        pathBuilder8.lineToRelative(1.12f, -2.0f);
        pathBuilder8.horizontalLineToRelative(2.14f);
        pathBuilder8.lineToRelative(1.12f, 2.0f);
        pathBuilder8.lineTo(8.06f, 17.0f);
        pathBuilder8.close();
        pathBuilder8.moveTo(8.06f, 11.0f);
        pathBuilder8.horizontalLineTo(5.92f);
        pathBuilder8.lineTo(4.79f, 9.0f);
        pathBuilder8.lineToRelative(1.12f, -2.0f);
        pathBuilder8.horizontalLineToRelative(2.14f);
        pathBuilder8.lineToRelative(1.12f, 2.0f);
        pathBuilder8.lineTo(8.06f, 11.0f);
        pathBuilder8.close();
        pathBuilder8.moveTo(13.08f, 20.0f);
        pathBuilder8.horizontalLineToRelative(-2.16f);
        pathBuilder8.lineTo(9.8f, 18.02f);
        pathBuilder8.lineTo(10.94f, 16.0f);
        pathBuilder8.horizontalLineToRelative(2.12f);
        pathBuilder8.lineToRelative(1.13f, 2.02f);
        pathBuilder8.lineTo(13.08f, 20.0f);
        pathBuilder8.close();
        pathBuilder8.moveTo(9.81f, 12.0f);
        pathBuilder8.lineToRelative(1.12f, -2.0f);
        pathBuilder8.horizontalLineToRelative(2.12f);
        pathBuilder8.lineToRelative(1.12f, 2.0f);
        pathBuilder8.lineToRelative(-1.12f, 2.0f);
        pathBuilder8.horizontalLineToRelative(-2.12f);
        pathBuilder8.lineTo(9.81f, 12.0f);
        pathBuilder8.close();
        pathBuilder8.moveTo(13.06f, 8.0f);
        pathBuilder8.horizontalLineToRelative(-2.12f);
        pathBuilder8.lineTo(9.8f, 5.98f);
        pathBuilder8.lineTo(10.92f, 4.0f);
        pathBuilder8.horizontalLineToRelative(2.16f);
        pathBuilder8.lineToRelative(1.12f, 1.98f);
        pathBuilder8.lineTo(13.06f, 8.0f);
        pathBuilder8.close();
        pathBuilder8.moveTo(18.08f, 17.0f);
        pathBuilder8.horizontalLineToRelative(-2.14f);
        pathBuilder8.lineToRelative(-1.12f, -2.0f);
        pathBuilder8.lineToRelative(1.12f, -2.0f);
        pathBuilder8.horizontalLineToRelative(2.14f);
        pathBuilder8.lineToRelative(1.12f, 2.0f);
        pathBuilder8.lineTo(18.08f, 17.0f);
        pathBuilder8.close();
        pathBuilder8.moveTo(18.08f, 11.0f);
        pathBuilder8.horizontalLineToRelative(-2.14f);
        pathBuilder8.lineToRelative(-1.12f, -2.0f);
        pathBuilder8.lineToRelative(1.12f, -2.0f);
        pathBuilder8.horizontalLineToRelative(2.14f);
        pathBuilder8.lineToRelative(1.12f, 2.0f);
        pathBuilder8.lineTo(18.08f, 11.0f);
        pathBuilder8.close();
        ImageVector imageVectorBuild = ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder8.getNodes(), defaultFillType8, "", solidColor8, 1.0f, (Brush) null, 1.0f, 1.0f, i15, i16, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null).build();
        _hive = imageVectorBuild;
        imageVectorBuild.getClass();
        return imageVectorBuild;
    }
}
