package androidx.compose.material.icons.twotone;

import androidx.compose.material.icons.Icons;
import androidx.compose.ui.graphics.Brush;
import androidx.compose.ui.graphics.Color;
import androidx.compose.ui.graphics.SolidColor;
import androidx.compose.ui.graphics.StrokeCap;
import androidx.compose.ui.graphics.StrokeJoin;
import androidx.compose.ui.graphics.vector.ImageVector;
import androidx.compose.ui.graphics.vector.PathBuilder;
import androidx.compose.ui.graphics.vector.VectorKt;
import androidx.compose.ui.unit.Dp;
import kotlin.Metadata;
import kotlin.jvm.internal.DefaultConstructorMarker;

/* JADX INFO: loaded from: /workspace/dex_all/classes.dex */
@Metadata(d1 = {"\u0000\u0010\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\"\u0010\u0010\u0000\u001a\u0004\u0018\u00010\u0001X\u0082\u000e¢\u0006\u0002\n\u0000\"\u0015\u0010\u0002\u001a\u00020\u0001*\u00020\u00038F¢\u0006\u0006\u001a\u0004\b\u0004\u0010\u0005¨\u0006\u0006"}, d2 = {"_templeHindu", "Landroidx/compose/ui/graphics/vector/ImageVector;", "TempleHindu", "Landroidx/compose/material/icons/Icons$TwoTone;", "getTempleHindu", "(Landroidx/compose/material/icons/Icons$TwoTone;)Landroidx/compose/ui/graphics/vector/ImageVector;", "material-icons-extended_release"}, k = 2, mv = {1, 8, 0}, xi = 48)
public final class TempleHinduKt {
    private static ImageVector _templeHindu;

    public static final ImageVector getTempleHindu(Icons.TwoTone twoTone) {
        ImageVector imageVector = _templeHindu;
        if (imageVector != null) {
            imageVector.getClass();
            return imageVector;
        }
        ImageVector.Builder builder = new ImageVector.Builder("TwoTone.TempleHindu", Dp.constructor-impl(24.0f), Dp.constructor-impl(24.0f), 24.0f, 24.0f, 0L, 0, false, 96, (DefaultConstructorMarker) null);
        int defaultFillType = VectorKt.getDefaultFillType();
        Color.Companion companion = Color.Companion;
        SolidColor solidColor = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        StrokeCap.Companion companion2 = StrokeCap.Companion;
        int i = companion2.getButt-KaPHkGw();
        StrokeJoin.Companion companion3 = StrokeJoin.Companion;
        int i2 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder = new PathBuilder();
        pathBuilder.moveTo(13.51f, 5.0f);
        pathBuilder.lineToRelative(-3.02f, 0.0f);
        pathBuilder.lineToRelative(-0.6f, 2.0f);
        pathBuilder.lineToRelative(4.22f, 0.0f);
        pathBuilder.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder.getNodes(), defaultFillType, "", solidColor, 0.3f, (Brush) null, 0.3f, 1.0f, i, i2, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType2 = VectorKt.getDefaultFillType();
        SolidColor solidColor2 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i3 = companion2.getButt-KaPHkGw();
        int i4 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder2 = new PathBuilder();
        pathBuilder2.moveTo(14.71f, 9.0f);
        pathBuilder2.lineToRelative(-5.42f, 0.0f);
        pathBuilder2.lineToRelative(-0.6f, 2.0f);
        pathBuilder2.lineToRelative(6.62f, 0.0f);
        pathBuilder2.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder2.getNodes(), defaultFillType2, "", solidColor2, 0.3f, (Brush) null, 0.3f, 1.0f, i3, i4, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType3 = VectorKt.getDefaultFillType();
        SolidColor solidColor3 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i5 = companion2.getButt-KaPHkGw();
        int i6 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder3 = new PathBuilder();
        pathBuilder3.moveTo(15.91f, 13.0f);
        pathBuilder3.lineToRelative(-7.82f, 0.0f);
        pathBuilder3.lineToRelative(-0.6f, 2.0f);
        pathBuilder3.lineToRelative(-3.49f, 0.0f);
        pathBuilder3.lineToRelative(0.0f, 5.0f);
        pathBuilder3.lineToRelative(5.0f, 0.0f);
        pathBuilder3.lineToRelative(0.0f, -5.0f);
        pathBuilder3.lineToRelative(6.0f, 0.0f);
        pathBuilder3.lineToRelative(0.0f, 5.0f);
        pathBuilder3.lineToRelative(5.0f, 0.0f);
        pathBuilder3.lineToRelative(0.0f, -5.0f);
        pathBuilder3.lineToRelative(-3.49f, 0.0f);
        pathBuilder3.close();
        ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder3.getNodes(), defaultFillType3, "", solidColor3, 0.3f, (Brush) null, 0.3f, 1.0f, i5, i6, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int defaultFillType4 = VectorKt.getDefaultFillType();
        SolidColor solidColor4 = new SolidColor(companion.getBlack-0d7_KjU(), (DefaultConstructorMarker) null);
        int i7 = companion2.getButt-KaPHkGw();
        int i8 = companion3.getBevel-LxFBmk8();
        PathBuilder pathBuilder4 = new PathBuilder();
        pathBuilder4.moveTo(20.0f, 11.0f);
        pathBuilder4.verticalLineToRelative(2.0f);
        pathBuilder4.horizontalLineToRelative(-2.0f);
        pathBuilder4.lineTo(15.0f, 3.0f);
        pathBuilder4.verticalLineTo(1.0f);
        pathBuilder4.horizontalLineToRelative(-2.0f);
        pathBuilder4.verticalLineToRelative(2.0f);
        pathBuilder4.horizontalLineToRelative(-2.03f);
        pathBuilder4.verticalLineTo(1.0f);
        pathBuilder4.horizontalLineToRelative(-2.0f);
        pathBuilder4.verticalLineToRelative(2.12f);
        pathBuilder4.lineTo(6.0f, 13.0f);
        pathBuilder4.horizontalLineTo(4.0f);
        pathBuilder4.verticalLineToRelative(-2.0f);
        pathBuilder4.horizontalLineTo(2.0f);
        pathBuilder4.verticalLineToRelative(11.0f);
        pathBuilder4.horizontalLineToRelative(9.0f);
        pathBuilder4.verticalLineToRelative(-5.0f);
        pathBuilder4.horizontalLineToRelative(2.0f);
        pathBuilder4.verticalLineToRelative(5.0f);
        pathBuilder4.horizontalLineToRelative(9.0f);
        pathBuilder4.verticalLineTo(11.0f);
        pathBuilder4.horizontalLineTo(20.0f);
        pathBuilder4.close();
        pathBuilder4.moveTo(10.49f, 5.0f);
        pathBuilder4.horizontalLineToRelative(3.02f);
        pathBuilder4.lineToRelative(0.6f, 2.0f);
        pathBuilder4.horizontalLineTo(9.89f);
        pathBuilder4.lineTo(10.49f, 5.0f);
        pathBuilder4.close();
        pathBuilder4.moveTo(9.29f, 9.0f);
        pathBuilder4.horizontalLineToRelative(5.42f);
        pathBuilder4.lineToRelative(0.6f, 2.0f);
        pathBuilder4.horizontalLineTo(8.69f);
        pathBuilder4.lineTo(9.29f, 9.0f);
        pathBuilder4.close();
        pathBuilder4.moveTo(20.0f, 20.0f);
        pathBuilder4.horizontalLineToRelative(-5.0f);
        pathBuilder4.verticalLineToRelative(-5.0f);
        pathBuilder4.horizontalLineTo(9.0f);
        pathBuilder4.verticalLineToRelative(5.0f);
        pathBuilder4.horizontalLineTo(4.0f);
        pathBuilder4.verticalLineToRelative(-5.0f);
        pathBuilder4.horizontalLineToRelative(3.49f);
        pathBuilder4.lineToRelative(0.6f, -2.0f);
        pathBuilder4.horizontalLineToRelative(7.82f);
        pathBuilder4.lineToRelative(0.6f, 2.0f);
        pathBuilder4.horizontalLineTo(20.0f);
        pathBuilder4.verticalLineTo(20.0f);
        pathBuilder4.close();
        ImageVector imageVectorBuild = ImageVector.Builder.addPath-oIyEayM$default(builder, pathBuilder4.getNodes(), defaultFillType4, "", solidColor4, 1.0f, (Brush) null, 1.0f, 1.0f, i7, i8, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null).build();
        _templeHindu = imageVectorBuild;
        imageVectorBuild.getClass();
        return imageVectorBuild;
    }
}
